# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_jaw) {transformation: [0f,1f,0f,2f,1f,0f,0f,0f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [0f,1f,0f,1.875f,1f,0f,0f,0f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,1.2629f,0f,0f,0f,0.3125f,0f,0f,0f,0.1563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,1.2629f,0f,0f,0f,0.3125f,0f,0f,0f,0.1563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,1.2629f,0f,0f,0f,0.3125f,0f,0f,0f,0.1563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,1.2629f,0f,0f,0f,0.3125f,0f,0f,0f,0.1563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,1.2629f,0f,0f,0f,0.3125f,0f,0f,0f,0.1563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [0f,0.866f,-0.5f,1.75f,1f,0f,0f,0.3125f,0f,-0.5f,-0.866f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [0f,0.866f,-0.5f,1.75f,1f,0f,0f,-0.3125f,0f,-0.5f,-0.866f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [0.171f,0.377f,-0.9103f,1.125f,0.866f,-0.4981f,-0.0436f,0.125f,-0.4698f,-0.7809f,-0.4116f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-0.171f,0.377f,-0.9103f,1.125f,0.866f,0.4981f,0.0436f,-0.125f,0.4698f,-0.7809f,-0.4116f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [0f,1f,0f,1.875f,1f,0f,0f,0f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":1.2087341226347257,"py":0.31250000000000033,"pz":0.1875000000000001,"ry":330,"rx":-4.770832022195275e-15},"center":{"px":1.5,"py":3.3306690738754696e-16,"pz":-0.1249999999999998,"ry":0,"rx":0}}}