# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
particle poof ~ ~0.5 ~ 0.4 0.25 0.4 0.008 10 normal
function animated_java:skurleton/remove/this