# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.ridinggunshooting03.frame matches 12.. run scoreboard players set @s aj.ridinggunshooting03.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.ridinggunshooting03.frame
execute at @s run function animated_java:skurleton/animations/ridinggunshooting03/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.ridinggunshooting03.frame 1