# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [-1f,0f,0f,-0.1875f,0f,0.5f,-0.866f,0.4649f,0f,-0.866f,-0.5f,-0.0564f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1) {transformation: [-1f,0f,0f,0.1875f,0f,0.5f,-0.866f,0.4649f,0f,-0.866f,-0.5f,-0.0564f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.1875f,0f,0.5f,-0.866f,1.1144f,0f,-0.866f,-0.5f,0.3186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3) {transformation: [-1f,0f,0f,0.1875f,0f,0.5f,-0.866f,1.1144f,0f,-0.866f,-0.5f,0.3186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tie) {transformation: [-1f,0f,0f,0f,0f,0.5f,-0.866f,1.4944f,0f,-0.866f,-0.5f,0.2854f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mlg_glasses) {transformation: [-1f,0f,0f,0f,0f,0.5f,-0.866f,1.6891f,0f,-0.866f,-0.5f,0.0731f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.5f,-0.866f,1.4643f,0f,-0.866f,-0.5f,0.0876f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.5f,-0.866f,0.9542f,0f,-0.866f,-0.5f,-0.279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":0,"py":0.9375,"pz":0,"ry":0,"rx":-60}}}