# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:beebs/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.beebs.node.leg0] run data merge entity @s { transformation: [-1f,0f,0f,-0.1875f,0f,1f,0f,0.75f,0f,0f,-1f,-0.4375f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.beebs.node.leg1] run data merge entity @s { transformation: [-1f,0f,0f,0.1875f,0f,1f,0f,0.75f,0f,0f,-1f,-0.4375f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.beebs.node.leg2] run data merge entity @s { transformation: [-1f,0f,0f,-0.1875f,0f,1f,0f,0.75f,0f,0f,-1f,0.3125f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.beebs.node.leg3] run data merge entity @s { transformation: [-1f,0f,0f,0.1875f,0f,1f,0f,0.75f,0f,0f,-1f,0.3125f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.beebs.node.tie] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.9688f,0f,0f,-1f,0.625f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.beebs.node.mlg_glasses] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.25f,0f,0f,-1f,0.6875f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.beebs.node.head] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.125f,0f,0f,-1f,0.5f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.beebs.node.body] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.1875f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: 0 }