# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data merge entity @s {Invulnerable:1b,Marker:1b,Invisible:1b}
function animated_java:global/util/get_entity_stack_uuids