# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data merge entity @e[tag=Spite,limit=1] {NoAI:0}
function animated_java:spite/animations/idle01/tween {duration:8,to_frame:0}
tag @s remove PreparingFireball
tag @s remove Fireballing