# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:spite/at_locator {name:"fireballspawn",command:'summon small_fireball ~ ~ ~ {Tags:["SpiteFB"]}'}
function animated_java:spite/at_locator {name:"fireballspawn",command:'execute facing entity @p eyes run summon marker ^ ^ ^-1 {Tags:["Aim"]}'}
function animated_java:spite/at_locator {name:"fireballspawn",command:'playsound minecraft:item.firecharge.use hostile @a ~ ~ ~ 1 1.125'}