# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
summon minecraft:marker ^0 ^0.9375 ^0 {Tags:["aj.beebs.bone.body.child","aj.beebs.bone.body.child.locator","aj.beebs.bone.body.decendant","aj.beebs.bone.body.decendant.locator","aj.beebs.bone.body.tree","aj.beebs.bone.middlerotationpoint.decendant","aj.beebs.bone.middlerotationpoint.decendant.locator","aj.beebs.bone.middlerotationpoint.tree","aj.beebs.bone.root.decendant","aj.beebs.bone.root.decendant.locator","aj.beebs.bone.root.tree","aj.beebs.entity","aj.beebs.locator","aj.beebs.locator.center","aj.beebs.node","aj.beebs.node.center","aj.global.bone.body.child","aj.global.bone.body.child.locator","aj.global.bone.body.decendant","aj.global.bone.body.decendant.locator","aj.global.bone.body.tree","aj.global.bone.middlerotationpoint.decendant","aj.global.bone.middlerotationpoint.decendant.locator","aj.global.bone.middlerotationpoint.tree","aj.global.bone.root.decendant","aj.global.bone.root.decendant.locator","aj.global.bone.root.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.center","aj.new"]}
execute as @n[ type=minecraft:marker, tag=aj.beebs.locator.center, tag=aj.new, distance=..2 ] run function animated_java:beebs/zzz/summon/as_data_entity/as_locator/center
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.locator_center set from storage animated_java:gu out
data modify entity @s data.locators.center.uuid set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.beebs.node.leg0] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leg0 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.beebs.node.leg1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leg1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.beebs.node.leg2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leg2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.beebs.node.leg3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leg3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.beebs.node.tie] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_tie set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.beebs.node.mlg_glasses] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_mlg_glasses set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.beebs.node.head] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.beebs.node.body] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_body set from storage animated_java:gu out