# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:beebs/animations/pause_all
tag @s add aj.beebs.animation.stomp01.playing
scoreboard players set @s aj.stomp01.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:beebs/animations/stomp01/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only