# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute as @e[tag=aj.spite.root,sort=nearest,limit=1] run function animated_java:spite/variants/damaged/apply
playsound minecraft:entity.vex.death hostile @a ~ ~ ~ 3 0.65
playsound minecraft:entity.wither.death hostile @a ~ ~ ~ 0.5 2