# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.skurleton.node.jaw] at @s run function animated_java:skurleton/variants/hurt/zzz/apply_to_node_jaw
execute on passengers if entity @s[tag=aj.skurleton.node.head] at @s run function animated_java:skurleton/variants/hurt/zzz/apply_to_node_head
execute on passengers if entity @s[tag=aj.skurleton.node.rightarm] at @s run function animated_java:skurleton/variants/hurt/zzz/apply_to_node_rightarm
execute on passengers if entity @s[tag=aj.skurleton.node.leftarm] at @s run function animated_java:skurleton/variants/hurt/zzz/apply_to_node_leftarm
execute on passengers if entity @s[tag=aj.skurleton.node.rightleg] at @s run function animated_java:skurleton/variants/hurt/zzz/apply_to_node_rightleg
execute on passengers if entity @s[tag=aj.skurleton.node.leftleg] at @s run function animated_java:skurleton/variants/hurt/zzz/apply_to_node_leftleg
execute on passengers if entity @s[tag=aj.skurleton.node.body] at @s run function animated_java:skurleton/variants/hurt/zzz/apply_to_node_body
return 1