# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:skurleton/animations/sneaked02/zzz/apply_frame {frame: 200}
scoreboard players add @s aj.sneaked02.frame 1