# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.beebs.node.leg0] at @s run function animated_java:beebs/variants/black_hurt_beebs/zzz/apply_to_node_leg0
execute on passengers if entity @s[tag=aj.beebs.node.leg1] at @s run function animated_java:beebs/variants/black_hurt_beebs/zzz/apply_to_node_leg1
execute on passengers if entity @s[tag=aj.beebs.node.leg2] at @s run function animated_java:beebs/variants/black_hurt_beebs/zzz/apply_to_node_leg2
execute on passengers if entity @s[tag=aj.beebs.node.leg3] at @s run function animated_java:beebs/variants/black_hurt_beebs/zzz/apply_to_node_leg3
execute on passengers if entity @s[tag=aj.beebs.node.tie] at @s run function animated_java:beebs/variants/black_hurt_beebs/zzz/apply_to_node_tie
execute on passengers if entity @s[tag=aj.beebs.node.mlg_glasses] at @s run function animated_java:beebs/variants/black_hurt_beebs/zzz/apply_to_node_mlg_glasses
execute on passengers if entity @s[tag=aj.beebs.node.head] at @s run function animated_java:beebs/variants/black_hurt_beebs/zzz/apply_to_node_head
execute on passengers if entity @s[tag=aj.beebs.node.body] at @s run function animated_java:beebs/variants/black_hurt_beebs/zzz/apply_to_node_body
return 1