# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:skurleton/animations/ridingspin01/zzz/apply_frame {frame: 6}
scoreboard players add @s aj.ridingspin01.frame 1