# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_leg) {transformation: [-1f,0f,0f,0.125f,0f,0.5f,-0.866f,-1.1875f,0f,-0.866f,-0.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1f,0f,0f,-0.125f,0f,-0.342f,0.9397f,-1.1875f,0f,0.9397f,0.342f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arms) {transformation: [-1f,0f,0f,0f,0f,0.8286f,-0.5598f,-0.7898f,0f,-0.5598f,-0.8286f,0.4861f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.4728f,0.8812f,-0.7014f,0f,0.8812f,-0.4728f,0.6629f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.7071f,0.7071f,-1.1875f,0f,0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":-4.329780281177467e-17,"py":-0.8339466094067263,"pz":0.3535533905932738,"ry":0,"rx":45.00000000000001}}}