# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_arms) {transformation: [-1f,0f,0f,0f,0f,0.4753f,-0.8798f,-0.6273f,0f,-0.8798f,-0.4753f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9993f,0.0366f,-0.4398f,0f,0.0366f,-0.9993f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-1.2523f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":0,"py":-0.7523265018048846,"pz":0,"ry":0,"rx":0}}}