# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_arms) {transformation: [-1f,0f,0f,0f,0f,0.5059f,-0.8626f,-0.6332f,0f,-0.8626f,-0.5059f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9944f,0.1053f,-0.4457f,0f,0.1053f,-0.9944f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-1.2582f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^0 ^-0.7581513169 ^0 rotated ~0 ~0 run function animated_java:ravaged_mind/animations/idle01/zzz/frames/22_locator_center
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":0,"py":-0.758151316947937,"pz":0,"ry":0,"rx":0}}}