# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_arms) {transformation: [-1f,0f,0f,0f,0f,0.4691f,-0.8831f,-0.6263f,0f,-0.8831f,-0.4691f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9998f,0.0204f,-0.4388f,0f,0.0204f,-0.9998f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-1.2513f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":0,"py":-0.7512560118395208,"pz":0,"ry":0,"rx":0}}}