# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3684f,0f,0f,0f,0.8153f,0f,0f,0f,-0.002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3684f,0f,0f,0f,0.8153f,0f,0f,0f,-0.002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3684f,0f,0f,0f,0.8153f,0f,0f,0f,-0.002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3684f,0f,0f,0f,0.8153f,0f,0f,0f,-0.002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3684f,0f,0f,0f,0.8153f,0f,0f,0f,-0.002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.995f,0.0994f,0.0004f,-0.3125f,0.0994f,0.995f,0.0036f,1.375f,0f,0.0036f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.995f,-0.0994f,0.0004f,0.3125f,-0.0994f,0.995f,-0.0036f,1.375f,0f,-0.0036f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.37464347203033366,"py":0.7531012243139934,"pz":-0.002258690829048043,"ry":0.020588303121343188,"rx":0.20603588149855126}}}