# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3558f,0f,0f,0f,0.8144f,0f,0f,0f,-0.0159f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3558f,0f,0f,0f,0.8144f,0f,0f,0f,-0.0159f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3558f,0f,0f,0f,0.8144f,0f,0f,0f,-0.0159f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3558f,0f,0f,0f,0.8144f,0f,0f,0f,-0.0159f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3558f,0f,0f,0f,0.8144f,0f,0f,0f,-0.0159f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.997f,0.077f,0.0022f,-0.3125f,0.077f,0.9966f,0.0282f,1.375f,0f,0.0283f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.997f,-0.077f,0.0022f,0.3125f,-0.077f,0.9966f,-0.0282f,1.375f,0f,-0.0283f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.360610233245488,"py":0.7521048426579987,"pz":-0.01766432611078749,"ry":0.1247508454736419,"rx":1.6147513022445215}}}