# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.315f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.315f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.315f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.315f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.315f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0044f,0.0001f,-0.3125f,0.0044f,0.9998f,0.0185f,1.375f,0f,0.0185f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0044f,0.0001f,0.3125f,-0.0044f,0.9998f,-0.0185f,1.375f,0f,-0.0185f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.31527665496082047,"py":0.7501130160197007,"pz":-0.011556272722365694,"ry":0.004708155493233335,"rx":1.0594509602669255}}}