# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3161f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0086f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3161f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0086f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3161f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0086f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3161f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0086f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3161f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0086f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0065f,0.0001f,-0.3125f,0.0065f,0.9999f,0.0154f,1.375f,0f,0.0154f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0065f,0.0001f,0.3125f,-0.0065f,0.9999f,-0.0154f,1.375f,0f,-0.0154f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3165493820472109,"py":0.7500868223943655,"pz":-0.009598070632395253,"ry":0.005702138015010405,"rx":0.8799024157492765}}}