# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3175f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3175f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3175f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3175f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3175f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0089f,0.0001f,-0.3125f,0.0089f,0.9999f,0.0122f,1.375f,0f,0.0122f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0089f,0.0001f,0.3125f,-0.0089f,0.9999f,-0.0122f,1.375f,0f,-0.0122f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3180423273854643,"py":0.7500707517935405,"pz":-0.007597193117309259,"ry":0.0061769219349514515,"rx":0.6964491248422494}}}