# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.319f,0f,0f,0f,0.8126f,0f,0f,0f,-0.005f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.319f,0f,0f,0f,0.8126f,0f,0f,0f,-0.005f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.319f,0f,0f,0f,0.8126f,0f,0f,0f,-0.005f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.319f,0f,0f,0f,0.8126f,0f,0f,0f,-0.005f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.319f,0f,0f,0f,0.8126f,0f,0f,0f,-0.005f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9999f,0.0116f,0.0001f,-0.3125f,0.0116f,0.9999f,0.0089f,1.375f,0f,0.0089f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9999f,-0.0116f,0.0001f,0.3125f,-0.0116f,0.9999f,-0.0089f,1.375f,0f,-0.0089f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.31974337001937553,"py":0.7500667301051576,"pz":-0.0055625326338304545,"ry":0.005910309741011588,"rx":0.5099079106770926}}}