# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3207f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0032f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3207f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0032f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3207f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0032f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3207f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0032f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3207f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0032f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9999f,0.0146f,0.0001f,-0.3125f,0.0146f,0.9999f,0.0056f,1.375f,0f,0.0056f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9999f,-0.0146f,0.0001f,0.3125f,-0.0146f,0.9999f,-0.0056f,1.375f,0f,-0.0056f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3216386784696165,"py":0.7500766346152513,"pz":-0.0035031346004558038,"ry":0.004695874297908631,"rx":0.32111107217577894}}}