# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3226f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3226f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3226f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3226f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3226f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9998f,0.0179f,0f,-0.3125f,0.0179f,0.9998f,0.0023f,1.375f,0f,0.0023f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9998f,-0.0179f,0f,0.3125f,-0.0179f,0.9998f,-0.0023f,1.375f,0f,-0.0023f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.32371282273411084,"py":0.7501022219792617,"pz":-0.001428156531175797,"ry":0.002348851885528802,"rx":0.13090278912980485}}}