# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3267f,0f,0f,0f,0.8127f,0f,0f,0f,0.0025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3267f,0f,0f,0f,0.8127f,0f,0f,0f,0.0025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3267f,0f,0f,0f,0.8127f,0f,0f,0f,0.0025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3267f,0f,0f,0f,0.8127f,0f,0f,0f,0.0025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3267f,0f,0f,0f,0.8127f,0f,0f,0f,0.0025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9997f,0.0253f,-0.0001f,-0.3125f,0.0253f,0.9997f,-0.0044f,1.375f,0f,-0.0044f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9997f,-0.0253f,-0.0001f,0.3125f,-0.0253f,0.9997f,0.0044f,1.375f,0f,0.0044f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.32832867832055757,"py":0.750206441043632,"pz":0.0027315982976625058,"ry":359.9936579103264,"rx":-0.2503349601163179}}}