# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.329f,0f,0f,0f,0.8128f,0f,0f,0f,0.0043f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.329f,0f,0f,0f,0.8128f,0f,0f,0f,0.0043f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.329f,0f,0f,0f,0.8128f,0f,0f,0f,0.0043f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.329f,0f,0f,0f,0.8128f,0f,0f,0f,0.0043f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.329f,0f,0f,0f,0.8128f,0f,0f,0f,0.0043f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9996f,0.0293f,-0.0002f,-0.3125f,0.0293f,0.9995f,-0.0077f,1.375f,0f,-0.0077f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9996f,-0.0293f,-0.0002f,0.3125f,-0.0293f,0.9995f,0.0077f,1.375f,0f,0.0077f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3308327413908764,"py":0.7502873532613803,"pz":0.004797874313055996,"ry":359.9870977793985,"rx":-0.4396517653337014}}}