# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3313f,0f,0f,0f,0.8128f,0f,0f,0f,0.0062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3313f,0f,0f,0f,0.8128f,0f,0f,0f,0.0062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3313f,0f,0f,0f,0.8128f,0f,0f,0f,0.0062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3313f,0f,0f,0f,0.8128f,0f,0f,0f,0.0062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3313f,0f,0f,0f,0.8128f,0f,0f,0f,0.0062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9994f,0.0335f,-0.0004f,-0.3125f,0.0335f,0.9994f,-0.0109f,1.375f,0f,-0.0109f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9994f,-0.0335f,-0.0004f,0.3125f,-0.0335f,0.9994f,0.0109f,1.375f,0f,0.0109f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.33344065918074894,"py":0.7503883889116177,"pz":0.006842812773360711,"ry":359.97897966437495,"rx":-0.6269631364050154}}}