# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3535f,0f,0f,0f,0.8142f,0f,0f,0f,-0.0168f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3535f,0f,0f,0f,0.8142f,0f,0f,0f,-0.0168f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3535f,0f,0f,0f,0.8142f,0f,0f,0f,-0.0168f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3535f,0f,0f,0f,0.8142f,0f,0f,0f,-0.0168f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3535f,0f,0f,0f,0.8142f,0f,0f,0f,-0.0168f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9973f,0.0729f,0.0022f,-0.3125f,0.0729f,0.9969f,0.0298f,1.375f,0f,0.0299f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9973f,-0.0729f,0.0022f,0.3125f,-0.0729f,0.9969f,-0.0298f,1.375f,0f,-0.0299f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3580368762862062,"py":0.7519412995936823,"pz":-0.01868819804275222,"ry":0.12493411343646699,"rx":1.7089038024752876}}}