# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3338f,0f,0f,0f,0.813f,0f,0f,0f,0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3338f,0f,0f,0f,0.813f,0f,0f,0f,0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3338f,0f,0f,0f,0.813f,0f,0f,0f,0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3338f,0f,0f,0f,0.813f,0f,0f,0f,0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3338f,0f,0f,0f,0.813f,0f,0f,0f,0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9993f,0.0378f,-0.0005f,-0.3125f,0.0378f,0.9992f,-0.0142f,1.375f,0f,-0.0142f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9993f,-0.0378f,-0.0005f,0.3125f,-0.0378f,0.9992f,0.0142f,1.375f,0f,0.0142f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3361311567155871,"py":0.7505097148196295,"pz":0.008857321695794477,"ry":359.96929301433283,"rx":-0.8114258440366571}}}