# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3362f,0f,0f,0f,0.8131f,0f,0f,0f,0.0097f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3362f,0f,0f,0f,0.8131f,0f,0f,0f,0.0097f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3362f,0f,0f,0f,0.8131f,0f,0f,0f,0.0097f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3362f,0f,0f,0f,0.8131f,0f,0f,0f,0.0097f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3362f,0f,0f,0f,0.8131f,0f,0f,0f,0.0097f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9991f,0.0422f,-0.0007f,-0.3125f,0.0422f,0.999f,-0.0173f,1.375f,0f,-0.0173f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9991f,-0.0422f,-0.0007f,0.3125f,-0.0422f,0.999f,0.0173f,1.375f,0f,0.0173f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.33888229495841216,"py":0.7506510329900096,"pz":0.010832446920485673,"ry":359.95806929726825,"rx":-0.9922097986961279}}}