# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3413f,0f,0f,0f,0.8134f,0f,0f,0f,0.0132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3413f,0f,0f,0f,0.8134f,0f,0f,0f,0.0132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3413f,0f,0f,0f,0.8134f,0f,0f,0f,0.0132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3413f,0f,0f,0f,0.8134f,0f,0f,0f,0.0132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3413f,0f,0f,0f,0.8134f,0f,0f,0f,0.0132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9987f,0.0512f,-0.0012f,-0.3125f,0.0512f,0.9984f,-0.0234f,1.375f,0f,-0.0234f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9987f,-0.0512f,-0.0012f,0.3125f,-0.0512f,0.9984f,0.0234f,1.375f,0f,0.0234f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3444765362517416,"py":0.7509900047488755,"pz":0.0146296601475414,"ry":359.93134596535185,"rx":-1.3395130650197857}}}