# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3438f,0f,0f,0f,0.8136f,0f,0f,0f,0.0148f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3438f,0f,0f,0f,0.8136f,0f,0f,0f,0.0148f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3438f,0f,0f,0f,0.8136f,0f,0f,0f,0.0148f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3438f,0f,0f,0f,0.8136f,0f,0f,0f,0.0148f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3438f,0f,0f,0f,0.8136f,0f,0f,0f,0.0148f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9984f,0.0556f,-0.0015f,-0.3125f,0.0557f,0.9981f,-0.0263f,1.375f,0f,-0.0263f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9984f,-0.0556f,-0.0015f,0.3125f,-0.0557f,0.9981f,0.0263f,1.375f,0f,0.0263f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.34727413090961357,"py":0.7511845991886812,"pz":0.01643488758996448,"ry":359.9161147282745,"rx":-1.5044769515448098}}}