# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3463f,0f,0f,0f,0.8138f,0f,0f,0f,0.0164f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3463f,0f,0f,0f,0.8138f,0f,0f,0f,0.0164f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3463f,0f,0f,0f,0.8138f,0f,0f,0f,0.0164f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3463f,0f,0f,0f,0.8138f,0f,0f,0f,0.0164f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3463f,0f,0f,0f,0.8138f,0f,0f,0f,0.0164f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9982f,0.0601f,-0.0017f,-0.3125f,0.0601f,0.9978f,-0.029f,1.375f,0f,-0.0291f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9982f,-0.0601f,-0.0017f,0.3125f,-0.0601f,0.9978f,0.029f,1.375f,0f,0.0291f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.350041732202937,"py":0.7513930922888544,"pz":0.018167085571045766,"ry":359.8998781605808,"rx":-1.662659349556177}}}