# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3487f,0f,0f,0f,0.814f,0f,0f,0f,0.0178f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3487f,0f,0f,0f,0.814f,0f,0f,0f,0.0178f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3487f,0f,0f,0f,0.814f,0f,0f,0f,0.0178f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3487f,0f,0f,0f,0.814f,0f,0f,0f,0.0178f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3487f,0f,0f,0f,0.814f,0f,0f,0f,0.0178f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9979f,0.0644f,-0.002f,-0.3125f,0.0644f,0.9974f,-0.0316f,1.375f,0f,-0.0317f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9979f,-0.0644f,-0.002f,0.3125f,-0.0644f,0.9974f,0.0316f,1.375f,0f,0.0317f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.35275691491397637,"py":0.7516127969312583,"pz":0.019818573403254863,"ry":359.88285823123385,"rx":-1.813359150389121}}}