# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3511f,0f,0f,0f,0.8142f,0f,0f,0f,0.0192f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3511f,0f,0f,0f,0.8142f,0f,0f,0f,0.0192f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3511f,0f,0f,0f,0.8142f,0f,0f,0f,0.0192f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3511f,0f,0f,0f,0.8142f,0f,0f,0f,0.0192f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3511f,0f,0f,0f,0.8142f,0f,0f,0f,0.0192f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9976f,0.0686f,-0.0023f,-0.3125f,0.0687f,0.9971f,-0.0341f,1.375f,0f,-0.0342f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9976f,-0.0686f,-0.0023f,0.3125f,-0.0687f,0.9971f,0.0341f,1.375f,0f,0.0342f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.35539772199025077,"py":0.751840635055143,"pz":0.021382032868031666,"ry":359.86530433430437,"rx":-1.9559122659068655}}}