# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3534f,0f,0f,0f,0.8144f,0f,0f,0f,0.0206f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3534f,0f,0f,0f,0.8144f,0f,0f,0f,0.0206f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3534f,0f,0f,0f,0.8144f,0f,0f,0f,0.0206f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3534f,0f,0f,0f,0.8144f,0f,0f,0f,0.0206f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3534f,0f,0f,0f,0.8144f,0f,0f,0f,0.0206f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9973f,0.0727f,-0.0027f,-0.3125f,0.0728f,0.9967f,-0.0365f,1.375f,0f,-0.0366f,-0.9993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9973f,-0.0727f,-0.0027f,0.3125f,-0.0728f,0.9967f,0.0365f,1.375f,0f,0.0366f,-0.9993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3579428435686045,"py":0.752073197899791,"pz":0.02285054033510749,"ry":359.8474878463645,"rx":-2.0896946525365556}}}