# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3556f,0f,0f,0f,0.8146f,0f,0f,0f,0.0218f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3556f,0f,0f,0f,0.8146f,0f,0f,0f,0.0218f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3556f,0f,0f,0f,0.8146f,0f,0f,0f,0.0218f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3556f,0f,0f,0f,0.8146f,0f,0f,0f,0.0218f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3556f,0f,0f,0f,0.8146f,0f,0f,0f,0.0218f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9971f,0.0766f,-0.003f,-0.3125f,0.0767f,0.9963f,-0.0386f,1.375f,0f,-0.0387f,-0.9992f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9971f,-0.0766f,-0.003f,0.3125f,-0.0767f,0.9963f,0.0386f,1.375f,0f,0.0387f,-0.9992f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.36037178849596874,"py":0.752306817234055,"pz":0.02421759697027467,"ry":359.8296961102425,"rx":-2.2141249575675763}}}