# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3511f,0f,0f,0f,0.8141f,0f,0f,0f,-0.0176f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3511f,0f,0f,0f,0.8141f,0f,0f,0f,-0.0176f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3511f,0f,0f,0f,0.8141f,0f,0f,0f,-0.0176f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3511f,0f,0f,0f,0.8141f,0f,0f,0f,-0.0176f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3511f,0f,0f,0f,0.8141f,0f,0f,0f,-0.0176f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9976f,0.0685f,0.0021f,-0.3125f,0.0686f,0.9972f,0.0312f,1.375f,0f,0.0313f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9976f,-0.0685f,0.0021f,0.3125f,-0.0686f,0.9972f,-0.0312f,1.375f,0f,-0.0313f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.35534022838861024,"py":0.7517767236581688,"pz":-0.019556652509189497,"ry":0.12300808431041332,"rx":1.788891735985476}}}