# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3596f,0f,0f,0f,0.815f,0f,0f,0f,0.024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3596f,0f,0f,0f,0.815f,0f,0f,0f,0.024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3596f,0f,0f,0f,0.815f,0f,0f,0f,0.024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3596f,0f,0f,0f,0.815f,0f,0f,0f,0.024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3596f,0f,0f,0f,0.815f,0f,0f,0f,0.024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9965f,0.0837f,-0.0036f,-0.3125f,0.0838f,0.9956f,-0.0424f,1.375f,0f,-0.0426f,-0.9991f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9965f,-0.0837f,-0.0036f,0.3125f,-0.0838f,0.9956f,0.0424f,1.375f,0f,0.0426f,-0.9991f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3648042426960758,"py":0.7527617439615197,"pz":0.02662365335900885,"ry":359.7953771655592,"rx":-2.432830505179867}}}