# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3613f,0f,0f,0f,0.8152f,0f,0f,0f,0.0249f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3613f,0f,0f,0f,0.8152f,0f,0f,0f,0.0249f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3613f,0f,0f,0f,0.8152f,0f,0f,0f,0.0249f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3613f,0f,0f,0f,0.8152f,0f,0f,0f,0.0249f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3613f,0f,0f,0f,0.8152f,0f,0f,0f,0.0249f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9962f,0.0868f,-0.0038f,-0.3125f,0.0869f,0.9952f,-0.0441f,1.375f,0f,-0.0442f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9962f,-0.0868f,-0.0038f,0.3125f,-0.0869f,0.9952f,0.0441f,1.375f,0f,0.0442f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.36677227467508666,"py":0.7529751726329577,"pz":0.02765202235991455,"ry":359.7794452958692,"rx":-2.526174847711586}}}