# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3644f,0f,0f,0f,0.8155f,0f,0f,0f,0.0264f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3644f,0f,0f,0f,0.8155f,0f,0f,0f,0.0264f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3644f,0f,0f,0f,0.8155f,0f,0f,0f,0.0264f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3644f,0f,0f,0f,0.8155f,0f,0f,0f,0.0264f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3644f,0f,0f,0f,0.8155f,0f,0f,0f,0.0264f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9957f,0.0922f,-0.0043f,-0.3125f,0.0923f,0.9946f,-0.0467f,1.375f,0f,-0.0469f,-0.9989f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9957f,-0.0922f,-0.0043f,0.3125f,-0.0923f,0.9946f,0.0467f,1.375f,0f,0.0469f,-0.9989f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.37013358048721035,"py":0.7533548241236323,"pz":0.02933676379330478,"ry":359.7514546771595,"rx":-2.6788880949522955}}}