# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3656f,0f,0f,0f,0.8157f,0f,0f,0f,0.027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3656f,0f,0f,0f,0.8157f,0f,0f,0f,0.027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3656f,0f,0f,0f,0.8157f,0f,0f,0f,0.027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3656f,0f,0f,0f,0.8157f,0f,0f,0f,0.027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3656f,0f,0f,0f,0.8157f,0f,0f,0f,0.027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9955f,0.0944f,-0.0045f,-0.3125f,0.0945f,0.9944f,-0.0478f,1.375f,0f,-0.048f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9955f,-0.0944f,-0.0045f,0.3125f,-0.0945f,0.9944f,0.0478f,1.375f,0f,0.048f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3715001269472779,"py":0.7535140045761708,"pz":0.029985705131899364,"ry":359.7399076132119,"rx":-2.737624490921751}}}