# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3666f,0f,0f,0f,0.8158f,0f,0f,0f,0.0275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3666f,0f,0f,0f,0.8158f,0f,0f,0f,0.0275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3666f,0f,0f,0f,0.8158f,0f,0f,0f,0.0275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3666f,0f,0f,0f,0.8158f,0f,0f,0f,0.0275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3666f,0f,0f,0f,0.8158f,0f,0f,0f,0.0275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9953f,0.0962f,-0.0047f,-0.3125f,0.0963f,0.9942f,-0.0486f,1.375f,0f,-0.0488f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9953f,-0.0962f,-0.0047f,0.3125f,-0.0963f,0.9942f,0.0486f,1.375f,0f,0.0488f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.37264224894303916,"py":0.7536486043178723,"pz":0.030501688083538196,"ry":359.7302890840858,"rx":-2.7842773216099634}}}