# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3674f,0f,0f,0f,0.8159f,0f,0f,0f,0.0278f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3674f,0f,0f,0f,0.8159f,0f,0f,0f,0.0278f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3674f,0f,0f,0f,0.8159f,0f,0f,0f,0.0278f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3674f,0f,0f,0f,0.8159f,0f,0f,0f,0.0278f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3674f,0f,0f,0f,0.8159f,0f,0f,0f,0.0278f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9952f,0.0977f,-0.0048f,-0.3125f,0.0978f,0.994f,-0.0492f,1.375f,0f,-0.0494f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9952f,-0.0977f,-0.0048f,0.3125f,-0.0978f,0.994f,0.0492f,1.375f,0f,0.0494f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3735509021010269,"py":0.7537560364033008,"pz":0.03088243914126468,"ry":359.7227800181506,"rx":-2.818658000182438}}}