# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.368f,0f,0f,0f,0.816f,0f,0f,0f,0.028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.368f,0f,0f,0f,0.816f,0f,0f,0f,0.028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.368f,0f,0f,0f,0.816f,0f,0f,0f,0.028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.368f,0f,0f,0f,0.816f,0f,0f,0f,0.028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.368f,0f,0f,0f,0.816f,0f,0f,0f,0.028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9951f,0.0988f,-0.0049f,-0.3125f,0.0989f,0.9939f,-0.0496f,1.375f,0f,-0.0498f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9951f,-0.0988f,-0.0049f,0.3125f,-0.0989f,0.9939f,0.0496f,1.375f,0f,0.0498f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.37421889757020343,"py":0.7538342151196085,"pz":0.03112628112457194,"ry":359.7175230801662,"rx":-2.8406291388758738}}}