# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3685f,0f,0f,0f,0.816f,0f,0f,0f,0.0279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3685f,0f,0f,0f,0.816f,0f,0f,0f,0.0279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3685f,0f,0f,0f,0.816f,0f,0f,0f,0.0279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3685f,0f,0f,0f,0.816f,0f,0f,0f,0.0279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3685f,0f,0f,0f,0.816f,0f,0f,0f,0.0279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.995f,0.0996f,-0.0049f,-0.3125f,0.0997f,0.9938f,-0.0494f,1.375f,0f,-0.0496f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.995f,-0.0996f,-0.0049f,0.3125f,-0.0997f,0.9938f,0.0494f,1.375f,0f,0.0496f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3747358397436425,"py":0.7538809108850004,"pz":0.031028654311085542,"ry":359.7160549719889,"rx":-2.8314771924161644}}}