# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3682f,0f,0f,0f,0.8159f,0f,0f,0f,0.0276f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3682f,0f,0f,0f,0.8159f,0f,0f,0f,0.0276f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3682f,0f,0f,0f,0.8159f,0f,0f,0f,0.0276f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3682f,0f,0f,0f,0.8159f,0f,0f,0f,0.0276f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3682f,0f,0f,0f,0.8159f,0f,0f,0f,0.0276f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9951f,0.0991f,-0.0049f,-0.3125f,0.0992f,0.9939f,-0.0489f,1.375f,0f,-0.0492f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9951f,-0.0991f,-0.0049f,0.3125f,-0.0992f,0.9939f,0.0489f,1.375f,0f,0.0492f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.37440789733620533,"py":0.7538328073553376,"pz":0.030720205555281935,"ry":359.7203725356592,"rx":-2.8034562413733664}}}