# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3677f,0f,0f,0f,0.8159f,0f,0f,0f,0.0272f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3677f,0f,0f,0f,0.8159f,0f,0f,0f,0.0272f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3677f,0f,0f,0f,0.8159f,0f,0f,0f,0.0272f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3677f,0f,0f,0f,0.8159f,0f,0f,0f,0.0272f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3677f,0f,0f,0f,0.8159f,0f,0f,0f,0.0272f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9952f,0.0981f,-0.0048f,-0.3125f,0.0982f,0.994f,-0.0482f,1.375f,0f,-0.0484f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9952f,-0.0981f,-0.0048f,0.3125f,-0.0982f,0.994f,0.0482f,1.375f,0f,0.0484f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.37383246938957904,"py":0.7537538985829915,"pz":0.030275562302695125,"ry":359.7270002443015,"rx":-2.7631024136257936}}}