# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.367f,0f,0f,0f,0.8158f,0f,0f,0f,0.0267f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.367f,0f,0f,0f,0.8158f,0f,0f,0f,0.0267f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.367f,0f,0f,0f,0.8158f,0f,0f,0f,0.0267f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.367f,0f,0f,0f,0.8158f,0f,0f,0f,0.0267f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.367f,0f,0f,0f,0.8158f,0f,0f,0f,0.0267f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9953f,0.0968f,-0.0046f,-0.3125f,0.0969f,0.9942f,-0.0473f,1.375f,0f,-0.0475f,-0.9989f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9953f,-0.0968f,-0.0046f,0.3125f,-0.0969f,0.9942f,0.0473f,1.375f,0f,0.0475f,-0.9989f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.37301408303845096,"py":0.7536457107670216,"pz":0.029696683414070977,"ry":359.735816604555,"rx":-2.7105826535278834}}}