# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.366f,0f,0f,0f,0.8157f,0f,0f,0f,0.0261f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.366f,0f,0f,0f,0.8157f,0f,0f,0f,0.0261f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.366f,0f,0f,0f,0.8157f,0f,0f,0f,0.0261f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.366f,0f,0f,0f,0.8157f,0f,0f,0f,0.0261f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.366f,0f,0f,0f,0.8157f,0f,0f,0f,0.0261f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9955f,0.0951f,-0.0044f,-0.3125f,0.0952f,0.9944f,-0.0462f,1.375f,0f,-0.0464f,-0.9989f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9955f,-0.0951f,-0.0044f,0.3125f,-0.0952f,0.9944f,0.0462f,1.375f,0f,0.0464f,-0.9989f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3719591902611362,"py":0.7535103302993162,"pz":0.028986119933944347,"ry":359.7466598795735,"rx":-2.646114043298971}}}