# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3649f,0f,0f,0f,0.8155f,0f,0f,0f,0.0253f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3649f,0f,0f,0f,0.8155f,0f,0f,0f,0.0253f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3649f,0f,0f,0f,0.8155f,0f,0f,0f,0.0253f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3649f,0f,0f,0f,0.8155f,0f,0f,0f,0.0253f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3649f,0f,0f,0f,0.8155f,0f,0f,0f,0.0253f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9956f,0.0931f,-0.0042f,-0.3125f,0.0932f,0.9946f,-0.0448f,1.375f,0f,-0.045f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9956f,-0.0931f,-0.0042f,0.3125f,-0.0932f,0.9946f,0.0448f,1.375f,0f,0.045f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3706761239757207,"py":0.7533503520959387,"pz":0.02814700445728209,"ry":359.7593317912897,"rx":-2.569963569521658}}}