# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3635f,0f,0f,0f,0.8154f,0f,0f,0f,0.0245f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3635f,0f,0f,0f,0.8154f,0f,0f,0f,0.0245f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3635f,0f,0f,0f,0.8154f,0f,0f,0f,0.0245f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3635f,0f,0f,0f,0.8154f,0f,0f,0f,0.0245f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3635f,0f,0f,0f,0.8154f,0f,0f,0f,0.0245f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9959f,0.0907f,-0.0039f,-0.3125f,0.0908f,0.9949f,-0.0433f,1.375f,0f,-0.0435f,-0.9991f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9959f,-0.0907f,-0.0039f,0.3125f,-0.0908f,0.9949f,0.0433f,1.375f,0f,0.0435f,-0.9991f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3691750404645549,"py":0.7531688153267021,"pz":0.027183038022707117,"ry":359.7736020599848,"rx":-2.482447802366335}}}