# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.362f,0f,0f,0f,0.8152f,0f,0f,0f,0.0235f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.362f,0f,0f,0f,0.8152f,0f,0f,0f,0.0235f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.362f,0f,0f,0f,0.8152f,0f,0f,0f,0.0235f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.362f,0f,0f,0f,0.8152f,0f,0f,0f,0.0235f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.362f,0f,0f,0f,0.8152f,0f,0f,0f,0.0235f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9961f,0.0879f,-0.0037f,-0.3125f,0.088f,0.9952f,-0.0416f,1.375f,0f,-0.0418f,-0.9991f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9961f,-0.0879f,-0.0037f,0.3125f,-0.088f,0.9952f,0.0416f,1.375f,0f,0.0418f,-0.9991f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.36746784806255106,"py":0.7529691283343996,"pz":0.026098474558979394,"ry":359.78921367365086,"rx":-2.3839324435856573}}}