# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3584f,0f,0f,0f,0.8148f,0f,0f,0f,0.0212f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3584f,0f,0f,0f,0.8148f,0f,0f,0f,0.0212f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3584f,0f,0f,0f,0.8148f,0f,0f,0f,0.0212f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3584f,0f,0f,0f,0.8148f,0f,0f,0f,0.0212f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3584f,0f,0f,0f,0.8148f,0f,0f,0f,0.0212f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9967f,0.0816f,-0.0031f,-0.3125f,0.0816f,0.996f,-0.0376f,1.375f,0f,-0.0377f,-0.9993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9967f,-0.0816f,-0.0031f,0.3125f,-0.0816f,0.996f,0.0376f,1.375f,0f,0.0377f,-0.9993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3634910062244743,"py":0.7525302738059908,"pz":0.023587226546817438,"ry":359.82333493507207,"rx":-2.1556074037158295}}}