# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3564f,0f,0f,0f,0.8146f,0f,0f,0f,0.02f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3564f,0f,0f,0f,0.8146f,0f,0f,0f,0.02f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3564f,0f,0f,0f,0.8146f,0f,0f,0f,0.02f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3564f,0f,0f,0f,0.8146f,0f,0f,0f,0.02f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3564f,0f,0f,0f,0.8146f,0f,0f,0f,0.02f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9969f,0.078f,-0.0028f,-0.3125f,0.0781f,0.9963f,-0.0354f,1.375f,0f,-0.0355f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9969f,-0.078f,-0.0028f,0.3125f,-0.0781f,0.9963f,0.0354f,1.375f,0f,0.0355f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3612531002150353,"py":0.7522989854171523,"pz":0.022171640825948788,"ry":359.8412519349914,"rx":-2.026767924633641}}}