# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3542f,0f,0f,0f,0.8144f,0f,0f,0f,0.0186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3542f,0f,0f,0f,0.8144f,0f,0f,0f,0.0186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3542f,0f,0f,0f,0.8144f,0f,0f,0f,0.0186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3542f,0f,0f,0f,0.8144f,0f,0f,0f,0.0186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3542f,0f,0f,0f,0.8144f,0f,0f,0f,0.0186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9972f,0.0742f,-0.0025f,-0.3125f,0.0742f,0.9967f,-0.033f,1.375f,0f,-0.0331f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9972f,-0.0742f,-0.0025f,0.3125f,-0.0742f,0.9967f,0.033f,1.375f,0f,0.0331f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.35887233483988135,"py":0.7520651159345609,"pz":0.020657608183813878,"ry":359.8593384409065,"rx":-1.888866682451702}}}