# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3496f,0f,0f,0f,0.8139f,0f,0f,0f,0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3496f,0f,0f,0f,0.8139f,0f,0f,0f,0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3496f,0f,0f,0f,0.8139f,0f,0f,0f,0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3496f,0f,0f,0f,0.8139f,0f,0f,0f,0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3496f,0f,0f,0f,0.8139f,0f,0f,0f,0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9978f,0.066f,-0.0018f,-0.3125f,0.066f,0.9974f,-0.0277f,1.375f,0f,-0.0278f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9978f,-0.066f,-0.0018f,0.3125f,-0.066f,0.9974f,0.0277f,1.375f,0f,0.0278f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.35375976605957127,"py":0.7516050908843479,"pz":0.017361422562604378,"ry":359.89484996439006,"rx":-1.5883068317296793}}}