# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3472f,0f,0f,0f,0.8137f,0f,0f,0f,0.014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3472f,0f,0f,0f,0.8137f,0f,0f,0f,0.014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3472f,0f,0f,0f,0.8137f,0f,0f,0f,0.014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3472f,0f,0f,0f,0.8137f,0f,0f,0f,0.014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3472f,0f,0f,0f,0.8137f,0f,0f,0f,0.014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9981f,0.0617f,-0.0015f,-0.3125f,0.0617f,0.9978f,-0.0249f,1.375f,0f,-0.025f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9981f,-0.0617f,-0.0015f,0.3125f,-0.0617f,0.9978f,0.0249f,1.375f,0f,0.025f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3510691822362597,"py":0.751386137725303,"pz":0.015593875735731146,"ry":359.9117271411748,"rx":-1.4269624461489618}}}