# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3447f,0f,0f,0f,0.8136f,0f,0f,0f,0.0124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3447f,0f,0f,0f,0.8136f,0f,0f,0f,0.0124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3447f,0f,0f,0f,0.8136f,0f,0f,0f,0.0124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3447f,0f,0f,0f,0.8136f,0f,0f,0f,0.0124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3447f,0f,0f,0f,0.8136f,0f,0f,0f,0.0124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9984f,0.0573f,-0.0013f,-0.3125f,0.0573f,0.9981f,-0.022f,1.375f,0f,-0.022f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9984f,-0.0573f,-0.0013f,0.3125f,-0.0573f,0.9981f,0.022f,1.375f,0f,0.022f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3483178483978193,"py":0.7511788510667583,"pz":0.013757030194088055,"ry":359.9276902240189,"rx":-1.259179297026673}}}