# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3422f,0f,0f,0f,0.8134f,0f,0f,0f,0.0107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3422f,0f,0f,0f,0.8134f,0f,0f,0f,0.0107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3422f,0f,0f,0f,0.8134f,0f,0f,0f,0.0107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3422f,0f,0f,0f,0.8134f,0f,0f,0f,0.0107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3422f,0f,0f,0f,0.8134f,0f,0f,0f,0.0107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9986f,0.0528f,-0.001f,-0.3125f,0.0529f,0.9984f,-0.0189f,1.375f,0f,-0.019f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9986f,-0.0528f,-0.001f,0.3125f,-0.0529f,0.9984f,0.0189f,1.375f,0f,0.019f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.34552806655285245,"py":0.7509859696718497,"pz":0.01185903762531797,"ry":359.94252864490386,"rx":-1.085701863481067}}}