# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3397f,0f,0f,0f,0.8132f,0f,0f,0f,0.0089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3397f,0f,0f,0f,0.8132f,0f,0f,0f,0.0089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3397f,0f,0f,0f,0.8132f,0f,0f,0f,0.0089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3397f,0f,0f,0f,0.8132f,0f,0f,0f,0.0089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3397f,0f,0f,0f,0.8132f,0f,0f,0f,0.0089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9988f,0.0484f,-0.0008f,-0.3125f,0.0484f,0.9987f,-0.0158f,1.375f,0f,-0.0159f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9988f,-0.0484f,-0.0008f,0.3125f,-0.0484f,0.9987f,0.0158f,1.375f,0f,0.0159f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.34272249073148275,"py":0.7508097836877434,"pz":0.009908325491417054,"ry":359.95606585343535,"rx":-0.9073034296965562}}}