# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3372f,0f,0f,0f,0.8131f,0f,0f,0f,0.0071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3372f,0f,0f,0f,0.8131f,0f,0f,0f,0.0071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3372f,0f,0f,0f,0.8131f,0f,0f,0f,0.0071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3372f,0f,0f,0f,0.8131f,0f,0f,0f,0.0071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3372f,0f,0f,0f,0.8131f,0f,0f,0f,0.0071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.999f,0.0439f,-0.0006f,-0.3125f,0.0439f,0.999f,-0.0126f,1.375f,0f,-0.0127f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.999f,-0.0439f,-0.0006f,0.3125f,-0.0439f,0.999f,0.0126f,1.375f,0f,0.0127f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3399239380129091,"py":0.750652097623439,"pz":0.007913559366830036,"ry":359.9681628731805,"rx":-0.7247821976589208}}}