# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3347f,0f,0f,0f,0.813f,0f,0f,0f,0.0053f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3347f,0f,0f,0f,0.813f,0f,0f,0f,0.0053f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3347f,0f,0f,0f,0.813f,0f,0f,0f,0.0053f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3347f,0f,0f,0f,0.813f,0f,0f,0f,0.0053f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3347f,0f,0f,0f,0.813f,0f,0f,0f,0.0053f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9992f,0.0394f,-0.0004f,-0.3125f,0.0395f,0.9992f,-0.0094f,1.375f,0f,-0.0094f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9992f,-0.0394f,-0.0004f,0.3125f,-0.0395f,0.9992f,0.0094f,1.375f,0f,0.0094f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.33715519676255545,"py":0.7505142079470846,"pz":0.005883604052155755,"ry":359.97872091362683,"rx":-0.538957161445407}}}