# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3322f,0f,0f,0f,0.8129f,0f,0f,0f,0.0034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3322f,0f,0f,0f,0.8129f,0f,0f,0f,0.0034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3322f,0f,0f,0f,0.8129f,0f,0f,0f,0.0034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3322f,0f,0f,0f,0.8129f,0f,0f,0f,0.0034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3322f,0f,0f,0f,0.8129f,0f,0f,0f,0.0034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9994f,0.0351f,-0.0002f,-0.3125f,0.0351f,0.9994f,-0.0061f,1.375f,0f,-0.0061f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9994f,-0.0351f,-0.0002f,0.3125f,-0.0351f,0.9994f,0.0061f,1.375f,0f,0.0061f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.33443883408569086,"py":0.7503968956786697,"pz":0.003827483653526381,"ry":359.98768297658427,"rx":-0.3506638008090602}}}