# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3299f,0f,0f,0f,0.8128f,0f,0f,0f,0.0016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3299f,0f,0f,0f,0.8128f,0f,0f,0f,0.0016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3299f,0f,0f,0f,0.8128f,0f,0f,0f,0.0016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3299f,0f,0f,0f,0.8128f,0f,0f,0f,0.0016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3299f,0f,0f,0f,0.8128f,0f,0f,0f,0.0016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9995f,0.0309f,-0.0001f,-0.3125f,0.0309f,0.9995f,-0.0028f,1.375f,0f,-0.0028f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9995f,-0.0309f,-0.0001f,0.3125f,-0.0309f,0.9995f,0.0028f,1.375f,0f,0.0028f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.33179700454933797,"py":0.7503004338854709,"pz":0.0017543408283097338,"ry":359.9950344210838,"rx":-0.16074965643521735}}}