# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3276f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3276f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3276f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3276f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3276f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9996f,0.0268f,0f,-0.3125f,0.0268f,0.9996f,0.0005f,1.375f,0f,0.0005f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9996f,-0.0268f,0f,0.3125f,-0.0268f,0.9996f,-0.0005f,1.375f,0f,-0.0005f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.32925126222146595,"py":0.7502246095248092,"pz":-0.00032660459345623503,"ry":0.0008024769039138846,"rx":0.02993014906781748}}}