# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3254f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0022f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3254f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0022f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3254f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0022f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3254f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0022f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3254f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0022f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9997f,0.0229f,0.0001f,-0.3125f,0.0229f,0.9997f,0.0038f,1.375f,0f,0.0038f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9997f,-0.0229f,0.0001f,0.3125f,-0.0229f,0.9997f,-0.0038f,1.375f,0f,-0.0038f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3268223780264397,"py":0.7501687586371903,"pz":-0.0024060973957958547,"ry":0.005054723086459489,"rx":0.22051738168975196}}}