# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3214f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0059f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3214f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0059f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3214f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0059f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3214f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0059f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3214f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0059f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9999f,0.0158f,0.0002f,-0.3125f,0.0158f,0.9998f,0.0104f,1.375f,0f,0.0104f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9999f,-0.0158f,0.0002f,0.3125f,-0.0158f,0.9998f,-0.0104f,1.375f,0f,-0.0104f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3223933084644756,"py":0.750112359897317,"pz":-0.006523779159839306,"ry":0.009467835752843712,"rx":0.5979919368949117}}}