# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3196f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0077f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3196f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0077f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3196f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0077f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3196f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0077f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3196f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0077f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9999f,0.0127f,0.0002f,-0.3125f,0.0127f,0.9998f,0.0137f,1.375f,0f,0.0137f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9999f,-0.0127f,0.0002f,0.3125f,-0.0127f,0.9998f,-0.0137f,1.375f,0f,-0.0137f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.320429216980359,"py":0.7501087027139852,"pz":-0.008543658132196052,"ry":0.009938433125483925,"rx":0.7831862274230825}}}