# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.318f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0095f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.318f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0095f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.318f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0095f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.318f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0095f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.318f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0095f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0098f,0.0002f,-0.3125f,0.0098f,0.9998f,0.0168f,1.375f,0f,0.0168f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0098f,0.0002f,0.3125f,-0.0098f,0.9998f,-0.0168f,1.375f,0f,-0.0168f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.31865387173691256,"py":0.7501189371450798,"pz":-0.01052554739436052,"ry":0.00950339793800481,"rx":0.9649099308766212}}}