# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3154f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3154f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3154f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3154f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3154f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0052f,0.0001f,-0.3125f,0.0052f,0.9997f,0.0229f,1.375f,0f,0.0229f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0052f,0.0001f,0.3125f,-0.0052f,0.9997f,-0.0229f,1.375f,0f,-0.0229f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.31572545475586483,"py":0.7501728630827061,"pz":-0.014340342163113915,"ry":0.006787998838547082,"rx":1.3147235873987615}}}