# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3144f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3144f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3144f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3144f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3144f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0034f,0.0001f,-0.3125f,0.0034f,0.9997f,0.0258f,1.375f,0f,0.0259f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0034f,0.0001f,0.3125f,-0.0034f,0.9997f,-0.0258f,1.375f,0f,-0.0259f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3145961199025051,"py":0.7502123720804995,"pz":-0.016156307748929306,"ry":0.00497062660190295,"rx":1.4812578580693383}}}