# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3136f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0161f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3136f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0161f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3136f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0161f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3136f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0161f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3136f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0161f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0019f,0.0001f,-0.3125f,0.0019f,0.9996f,0.0286f,1.375f,0f,0.0286f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0019f,0.0001f,0.3125f,-0.0019f,0.9996f,-0.0286f,1.375f,0f,-0.0286f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.31370281786424836,"py":0.7502575522175345,"pz":-0.017900479545497987,"ry":0.0031607018289037114,"rx":1.6412164765670598}}}