# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.313f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0176f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.313f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0176f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.313f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0176f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.313f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0176f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.313f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0176f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0009f,0f,-0.3125f,0.0009f,0.9995f,0.0313f,1.375f,0f,0.0313f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0009f,0f,0.3125f,-0.0009f,0.9995f,-0.0313f,1.375f,0f,-0.0313f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3130527430538318,"py":0.75030655483204,"pz":-0.01956512303312589,"ry":0.0015877944194926386,"rx":1.7938907277927694}}}