# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3125f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0204f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3125f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0204f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3125f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0204f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3125f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0204f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3125f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0204f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0f,0f,-0.3125f,0f,0.9993f,0.0362f,1.375f,0f,0.0362f,-0.9993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,0f,0f,0.3125f,0f,0.9993f,-0.0362f,1.375f,0f,-0.0362f,-0.9993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3125011039949208,"py":0.7504097085397542,"pz":-0.02262670573429488,"ry":0.000003668770773401775,"rx":2.0747169573224156}}}