# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3126f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0216f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3126f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0216f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3126f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0216f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3126f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0216f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3126f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0216f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0002f,0f,-0.3125f,0.0002f,0.9993f,0.0384f,1.375f,0f,0.0384f,-0.9993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0002f,0f,0.3125f,-0.0002f,0.9993f,-0.0384f,1.375f,0f,-0.0384f,-0.9993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3126038840803377,"py":0.7504613664570742,"pz":-0.024010089971361625,"ry":0.00036639268114413426,"rx":2.2016246361998144}}}