# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3129f,0f,0f,0f,0.813f,0f,0f,0f,-0.0228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3129f,0f,0f,0f,0.813f,0f,0f,0f,-0.0228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3129f,0f,0f,0f,0.813f,0f,0f,0f,-0.0228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3129f,0f,0f,0f,0.813f,0f,0f,0f,-0.0228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3129f,0f,0f,0f,0.813f,0f,0f,0f,-0.0228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0007f,0f,-0.3125f,0.0007f,0.9992f,0.0405f,1.375f,0f,0.0405f,-0.9992f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0007f,0f,0.3125f,-0.0007f,0.9992f,-0.0405f,1.375f,0f,-0.0405f,-0.9992f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3129585540537054,"py":0.7505119195124749,"pz":-0.025286894969254323,"ry":0.001703570586045089,"rx":2.3187640526675017}}}