# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3135f,0f,0f,0f,0.813f,0f,0f,0f,-0.0238f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3135f,0f,0f,0f,0.813f,0f,0f,0f,-0.0238f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3135f,0f,0f,0f,0.813f,0f,0f,0f,-0.0238f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3135f,0f,0f,0f,0.813f,0f,0f,0f,-0.0238f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3135f,0f,0f,0f,0.813f,0f,0f,0f,-0.0238f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0017f,0.0001f,-0.3125f,0.0017f,0.9991f,0.0423f,1.375f,0f,0.0423f,-0.9991f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0017f,0.0001f,0.3125f,-0.0017f,0.9991f,-0.0423f,1.375f,0f,-0.0423f,-0.9991f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3135621854686199,"py":0.750560898789883,"pz":-0.026451477121919642,"ry":0.004128492310627507,"rx":2.4256137785766994}}}