# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3142f,0f,0f,0f,0.813f,0f,0f,0f,-0.0247f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3142f,0f,0f,0f,0.813f,0f,0f,0f,-0.0247f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3142f,0f,0f,0f,0.813f,0f,0f,0f,-0.0247f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3142f,0f,0f,0f,0.813f,0f,0f,0f,-0.0247f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3142f,0f,0f,0f,0.813f,0f,0f,0f,-0.0247f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0031f,0.0001f,-0.3125f,0.0031f,0.999f,0.044f,1.375f,0f,0.044f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0031f,0.0001f,0.3125f,-0.0031f,0.999f,-0.044f,1.375f,0f,-0.044f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.31440984184338305,"py":0.7506081563344821,"pz":-0.02749869211632926,"ry":0.0077181562571695395,"rx":2.521696637357053}}}