# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3381f,0f,0f,0f,0.8134f,0f,0f,0f,-0.0194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3381f,0f,0f,0f,0.8134f,0f,0f,0f,-0.0194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3381f,0f,0f,0f,0.8134f,0f,0f,0f,-0.0194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3381f,0f,0f,0f,0.8134f,0f,0f,0f,-0.0194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3381f,0f,0f,0f,0.8134f,0f,0f,0f,-0.0194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.999f,0.0455f,0.0016f,-0.3125f,0.0455f,0.9984f,0.0344f,1.375f,0f,0.0345f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.999f,-0.0455f,0.0016f,0.3125f,-0.0455f,0.9984f,-0.0344f,1.375f,0f,-0.0345f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.34093791194701906,"py":0.7510188628852589,"pz":-0.021536612758003674,"ry":0.08994009259799896,"rx":1.972673707589427}}}