# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3152f,0f,0f,0f,0.8131f,0f,0f,0f,-0.0256f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3152f,0f,0f,0f,0.8131f,0f,0f,0f,-0.0256f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3152f,0f,0f,0f,0.8131f,0f,0f,0f,-0.0256f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3152f,0f,0f,0f,0.8131f,0f,0f,0f,-0.0256f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3152f,0f,0f,0f,0.8131f,0f,0f,0f,-0.0256f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0048f,0.0002f,-0.3125f,0.0048f,0.999f,0.0455f,1.375f,0f,0.0455f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0048f,0.0002f,0.3125f,-0.0048f,0.999f,-0.0455f,1.375f,0f,-0.0455f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.31549462058789346,"py":0.7506538514591656,"pz":-0.02842391686170046,"ry":0.012510869403399738,"rx":2.606581811802458}}}