# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3164f,0f,0f,0f,0.8131f,0f,0f,0f,-0.0263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3164f,0f,0f,0f,0.8131f,0f,0f,0f,-0.0263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3164f,0f,0f,0f,0.8131f,0f,0f,0f,-0.0263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3164f,0f,0f,0f,0.8131f,0f,0f,0f,-0.0263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3164f,0f,0f,0f,0.8131f,0f,0f,0f,-0.0263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0069f,0.0003f,-0.3125f,0.0069f,0.9989f,0.0468f,1.375f,0f,0.0468f,-0.9989f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0069f,0.0003f,0.3125f,-0.0069f,0.9989f,-0.0468f,1.375f,0f,-0.0468f,-0.9989f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.31680770986968676,"py":0.75069842554349,"pz":-0.029223069085934642,"ry":0.018504840683249313,"rx":2.679886889634219}}}