# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3193f,0f,0f,0f,0.8132f,0f,0f,0f,-0.0274f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3193f,0f,0f,0f,0.8132f,0f,0f,0f,-0.0274f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3193f,0f,0f,0f,0.8132f,0f,0f,0f,-0.0274f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3193f,0f,0f,0f,0.8132f,0f,0f,0f,-0.0274f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3193f,0f,0f,0f,0.8132f,0f,0f,0f,-0.0274f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9999f,0.0121f,0.0006f,-0.3125f,0.0121f,0.9987f,0.0487f,1.375f,0f,0.0487f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9999f,-0.0121f,0.0006f,0.3125f,-0.0121f,0.9987f,-0.0487f,1.375f,0f,-0.0487f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3200744688578964,"py":0.7507871637588902,"pz":-0.030429631830671895,"ry":0.03388770289220133,"rx":2.790480843537507}}}