# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3211f,0f,0f,0f,0.8132f,0f,0f,0f,-0.0277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3211f,0f,0f,0f,0.8132f,0f,0f,0f,-0.0277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3211f,0f,0f,0f,0.8132f,0f,0f,0f,-0.0277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3211f,0f,0f,0f,0.8132f,0f,0f,0f,-0.0277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3211f,0f,0f,0f,0.8132f,0f,0f,0f,-0.0277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9999f,0.0152f,0.0008f,-0.3125f,0.0152f,0.9987f,0.0493f,1.375f,0f,0.0493f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9999f,-0.0152f,0.0008f,0.3125f,-0.0152f,0.9987f,-0.0493f,1.375f,0f,-0.0493f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3220016808509473,"py":0.7508332572019782,"pz":-0.03083172466656574,"ry":0.04307436936719,"rx":2.827264103475248}}}