# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.325f,0f,0f,0f,0.8133f,0f,0f,0f,-0.0281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.325f,0f,0f,0f,0.8133f,0f,0f,0f,-0.0281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.325f,0f,0f,0f,0.8133f,0f,0f,0f,-0.0281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.325f,0f,0f,0f,0.8133f,0f,0f,0f,-0.0281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.325f,0f,0f,0f,0.8133f,0f,0f,0f,-0.0281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9998f,0.0222f,0.0011f,-0.3125f,0.0222f,0.9985f,0.0499f,1.375f,0f,0.05f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9998f,-0.0222f,0.0011f,0.3125f,-0.0222f,0.9985f,-0.0499f,1.375f,0f,-0.05f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.326365907824641,"py":0.7509344940723341,"pz":-0.03122468432898912,"ry":0.06366402863903886,"rx":2.862953130833217}}}