# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3294f,0f,0f,0f,0.8134f,0f,0f,0f,-0.028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3294f,0f,0f,0f,0.8134f,0f,0f,0f,-0.028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3294f,0f,0f,0f,0.8134f,0f,0f,0f,-0.028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3294f,0f,0f,0f,0.8134f,0f,0f,0f,-0.028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3294f,0f,0f,0f,0.8134f,0f,0f,0f,-0.028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9995f,0.0301f,0.0015f,-0.3125f,0.0301f,0.9983f,0.0497f,1.375f,0f,0.0497f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9995f,-0.0301f,0.0015f,0.3125f,-0.0301f,0.9983f,-0.0497f,1.375f,0f,-0.0497f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.33129017639927694,"py":0.7510553545213536,"pz":-0.031064588350890564,"ry":0.08582878233997349,"rx":2.84767345442318}}}