# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3318f,0f,0f,0f,0.8135f,0f,0f,0f,-0.0277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3318f,0f,0f,0f,0.8135f,0f,0f,0f,-0.0277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3318f,0f,0f,0f,0.8135f,0f,0f,0f,-0.0277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3318f,0f,0f,0f,0.8135f,0f,0f,0f,-0.0277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3318f,0f,0f,0f,0.8135f,0f,0f,0f,-0.0277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9994f,0.0343f,0.0017f,-0.3125f,0.0343f,0.9982f,0.0492f,1.375f,0f,0.0492f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9994f,-0.0343f,0.0017f,0.3125f,-0.0343f,0.9982f,-0.0492f,1.375f,0f,-0.0492f,-0.9988f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.33391319015715953,"py":0.751125644167995,"pz":-0.030777644849698166,"ry":0.09690214307744327,"rx":2.820965746381466}}}