# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3442f,0f,0f,0f,0.8139f,0f,0f,0f,-0.0246f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3442f,0f,0f,0f,0.8139f,0f,0f,0f,-0.0246f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3442f,0f,0f,0f,0.8139f,0f,0f,0f,-0.0246f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3442f,0f,0f,0f,0.8139f,0f,0f,0f,-0.0246f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3442f,0f,0f,0f,0.8139f,0f,0f,0f,-0.0246f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9984f,0.0564f,0.0025f,-0.3125f,0.0565f,0.9974f,0.0437f,1.375f,0f,0.0437f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9984f,-0.0564f,0.0025f,0.3125f,-0.0565f,0.9974f,-0.0437f,1.375f,0f,-0.0437f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.34777312914359515,"py":0.751595474991754,"pz":-0.02734235834127106,"ry":0.14173387131981485,"rx":2.5033564518888944}}}