# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3492f,0f,0f,0f,0.8142f,0f,0f,0f,-0.0226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3492f,0f,0f,0f,0.8142f,0f,0f,0f,-0.0226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3492f,0f,0f,0f,0.8142f,0f,0f,0f,-0.0226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3492f,0f,0f,0f,0.8142f,0f,0f,0f,-0.0226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3492f,0f,0f,0f,0.8142f,0f,0f,0f,-0.0226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9979f,0.0652f,0.0026f,-0.3125f,0.0652f,0.9971f,0.0401f,1.375f,0f,0.0402f,-0.9992f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9979f,-0.0652f,0.0026f,0.3125f,-0.0652f,0.9971f,-0.0401f,1.375f,0f,-0.0402f,-0.9992f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3532449123201904,"py":0.7518345726775516,"pz":-0.025093869969581333,"ry":0.15021153965244594,"rx":2.296149594488657}}}