# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3515f,0f,0f,0f,0.8143f,0f,0f,0f,-0.0214f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3515f,0f,0f,0f,0.8143f,0f,0f,0f,-0.0214f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3515f,0f,0f,0f,0.8143f,0f,0f,0f,-0.0214f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3515f,0f,0f,0f,0.8143f,0f,0f,0f,-0.0214f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3515f,0f,0f,0f,0.8143f,0f,0f,0f,-0.0214f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9976f,0.0694f,0.0026f,-0.3125f,0.0695f,0.9969f,0.038f,1.375f,0f,0.0381f,-0.9993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9976f,-0.0694f,0.0026f,0.3125f,-0.0695f,0.9969f,-0.038f,1.375f,0f,-0.0381f,-0.9993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.35587578816873766,"py":0.7519613952904212,"pz":-0.023799958871432873,"ry":0.15164056327049025,"rx":2.1770749495784303}}}