# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.356f,0f,0f,0f,0.8145f,0f,0f,0f,-0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.356f,0f,0f,0f,0.8145f,0f,0f,0f,-0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.356f,0f,0f,0f,0.8145f,0f,0f,0f,-0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.356f,0f,0f,0f,0.8145f,0f,0f,0f,-0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.356f,0f,0f,0f,0.8145f,0f,0f,0f,-0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.997f,0.0773f,0.0026f,-0.3125f,0.0774f,0.9964f,0.0333f,1.375f,0f,0.0334f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.997f,-0.0773f,0.0026f,0.3125f,-0.0774f,0.9964f,-0.0333f,1.375f,0f,-0.0334f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.36082117214176723,"py":0.7522213902594737,"pz":-0.020901377287223494,"ry":0.14830642684631812,"rx":1.9107095700954668}}}