# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.333f,0f,0f,0f,0.8132f,0f,0f,0f,-0.0191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.333f,0f,0f,0f,0.8132f,0f,0f,0f,-0.0191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.333f,0f,0f,0f,0.8132f,0f,0f,0f,-0.0191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.333f,0f,0f,0f,0.8132f,0f,0f,0f,-0.0191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.333f,0f,0f,0f,0.8132f,0f,0f,0f,-0.0191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9993f,0.0364f,0.0012f,-0.3125f,0.0364f,0.9988f,0.034f,1.375f,0f,0.034f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9993f,-0.0364f,0.0012f,0.3125f,-0.0364f,0.9988f,-0.034f,1.375f,0f,-0.034f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.33525971838884594,"py":0.7507761731568865,"pz":-0.02125109927037006,"ry":0.0710252950045458,"rx":1.9472384656631114}}}