# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.358f,0f,0f,0f,0.8146f,0f,0f,0f,-0.0174f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.358f,0f,0f,0f,0.8146f,0f,0f,0f,-0.0174f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.358f,0f,0f,0f,0.8146f,0f,0f,0f,-0.0174f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.358f,0f,0f,0f,0.8146f,0f,0f,0f,-0.0174f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.358f,0f,0f,0f,0.8146f,0f,0f,0f,-0.0174f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9967f,0.081f,0.0025f,-0.3125f,0.081f,0.9962f,0.0308f,1.375f,0f,0.0309f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9967f,-0.081f,0.0025f,0.3125f,-0.081f,0.9962f,-0.0308f,1.375f,0f,-0.0309f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.36309565182014786,"py":0.7523506428540037,"pz":-0.019309532945459656,"ry":0.14343706636668685,"rx":1.7646311511463106}}}