# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3599f,0f,0f,0f,0.8147f,0f,0f,0f,-0.0159f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3599f,0f,0f,0f,0.8147f,0f,0f,0f,-0.0159f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3599f,0f,0f,0f,0.8147f,0f,0f,0f,-0.0159f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3599f,0f,0f,0f,0.8147f,0f,0f,0f,-0.0159f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3599f,0f,0f,0f,0.8147f,0f,0f,0f,-0.0159f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9964f,0.0843f,0.0024f,-0.3125f,0.0844f,0.996f,0.0281f,1.375f,0f,0.0282f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9964f,-0.0843f,0.0024f,0.3125f,-0.0844f,0.996f,-0.0281f,1.375f,0f,-0.0282f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.365213078820988,"py":0.7524765491331213,"pz":-0.017631915437786447,"ry":0.13643488559807793,"rx":1.6108233256937237}}}