# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3633f,0f,0f,0f,0.8149f,0f,0f,0f,-0.0126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3633f,0f,0f,0f,0.8149f,0f,0f,0f,-0.0126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3633f,0f,0f,0f,0.8149f,0f,0f,0f,-0.0126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3633f,0f,0f,0f,0.8149f,0f,0f,0f,-0.0126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3633f,0f,0f,0f,0.8149f,0f,0f,0f,-0.0126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9959f,0.0903f,0.002f,-0.3125f,0.0903f,0.9957f,0.0224f,1.375f,0f,0.0225f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9959f,-0.0903f,0.002f,0.3125f,-0.0903f,0.9957f,-0.0224f,1.375f,0f,-0.0225f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.36890969141803936,"py":0.7527094251632196,"pz":-0.014049454915794556,"ry":0.11630401554063496,"rx":1.2828070405919405}}}