# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3647f,0f,0f,0f,0.815f,0f,0f,0f,-0.0109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3647f,0f,0f,0f,0.815f,0f,0f,0f,-0.0109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3647f,0f,0f,0f,0.815f,0f,0f,0f,-0.0109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3647f,0f,0f,0f,0.815f,0f,0f,0f,-0.0109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3647f,0f,0f,0f,0.815f,0f,0f,0f,-0.0109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9957f,0.0927f,0.0018f,-0.3125f,0.0928f,0.9955f,0.0194f,1.375f,0f,0.0195f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9957f,-0.0927f,0.0018f,0.3125f,-0.0928f,0.9955f,-0.0194f,1.375f,0f,-0.0195f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3704589981493357,"py":0.7528120246551987,"pz":-0.012160504506893178,"ry":0.103418689410546,"rx":1.110056781396929}}}