# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3669f,0f,0f,0f,0.8152f,0f,0f,0f,-0.0074f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3669f,0f,0f,0f,0.8152f,0f,0f,0f,-0.0074f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3669f,0f,0f,0f,0.8152f,0f,0f,0f,-0.0074f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3669f,0f,0f,0f,0.8152f,0f,0f,0f,-0.0074f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3669f,0f,0f,0f,0.8152f,0f,0f,0f,-0.0074f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9953f,0.0966f,0.0013f,-0.3125f,0.0966f,0.9952f,0.0131f,1.375f,0f,0.0132f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9953f,-0.0966f,0.0013f,0.3125f,-0.0966f,0.9952f,-0.0131f,1.375f,0f,-0.0132f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3728971361551605,"py":0.7529795272431067,"pz":-0.00822905921390295,"ry":0.072912869652356,"rx":0.7508748234300856}}}