# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3676f,0f,0f,0f,0.8152f,0f,0f,0f,-0.0056f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3676f,0f,0f,0f,0.8152f,0f,0f,0f,-0.0056f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3676f,0f,0f,0f,0.8152f,0f,0f,0f,-0.0056f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3676f,0f,0f,0f,0.8152f,0f,0f,0f,-0.0056f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3676f,0f,0f,0f,0.8152f,0f,0f,0f,-0.0056f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9952f,0.098f,0.001f,-0.3125f,0.098f,0.9951f,0.0099f,1.375f,0f,0.0099f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9952f,-0.098f,0.001f,0.3125f,-0.098f,0.9951f,-0.0099f,1.375f,0f,-0.0099f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3737662826363351,"py":0.7530410362345925,"pz":-0.006204031252761557,"ry":0.05575717513431755,"rx":0.5660134708874781}}}