# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3685f,0f,0f,0f,0.8153f,0f,0f,0f,-0.0019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3685f,0f,0f,0f,0.8153f,0f,0f,0f,-0.0019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3685f,0f,0f,0f,0.8153f,0f,0f,0f,-0.0019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3685f,0f,0f,0f,0.8153f,0f,0f,0f,-0.0019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3685f,0f,0f,0f,0.8153f,0f,0f,0f,-0.0019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.995f,0.0996f,0.0003f,-0.3125f,0.0996f,0.995f,0.0033f,1.375f,0f,0.0033f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.995f,-0.0996f,0.0003f,0.3125f,-0.0996f,0.995f,-0.0033f,1.375f,0f,-0.0033f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.37476971604442205,"py":0.7531132300182841,"pz":-0.0020803330155039477,"ry":0.01900102985121066,"rx":0.1897623180045855}}}