# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3679f,0f,0f,0f,0.8153f,0f,0f,0f,-0.004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3679f,0f,0f,0f,0.8153f,0f,0f,0f,-0.004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3679f,0f,0f,0f,0.8153f,0f,0f,0f,-0.004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3679f,0f,0f,0f,0.8153f,0f,0f,0f,-0.004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3679f,0f,0f,0f,0.8153f,0f,0f,0f,-0.004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9951f,0.0986f,0.0007f,-0.3125f,0.0986f,0.9951f,0.0071f,1.375f,0f,0.0071f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9951f,-0.0986f,0.0007f,0.3125f,-0.0986f,0.9951f,-0.0071f,1.375f,0f,-0.0071f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.37410050810057,"py":0.7530589101833456,"pz":-0.004433756807023751,"ry":0.04006273053727227,"rx":0.40448111719768864}}}