# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3305f,0f,0f,0f,0.8131f,0f,0f,0f,-0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3305f,0f,0f,0f,0.8131f,0f,0f,0f,-0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3305f,0f,0f,0f,0.8131f,0f,0f,0f,-0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3305f,0f,0f,0f,0.8131f,0f,0f,0f,-0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3305f,0f,0f,0f,0.8131f,0f,0f,0f,-0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9995f,0.0321f,0.0011f,-0.3125f,0.0321f,0.9989f,0.0334f,1.375f,0f,0.0334f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9995f,-0.0321f,0.0011f,0.3125f,-0.0321f,0.9989f,-0.0334f,1.375f,0f,-0.0334f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.33254672494618337,"py":0.7506710150995616,"pz":-0.020891324326622194,"ry":0.06149748351342055,"rx":1.914545294275049}}}