# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3282f,0f,0f,0f,0.813f,0f,0f,0f,-0.0184f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3282f,0f,0f,0f,0.813f,0f,0f,0f,-0.0184f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3282f,0f,0f,0f,0.813f,0f,0f,0f,-0.0184f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3282f,0f,0f,0f,0.813f,0f,0f,0f,-0.0184f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3282f,0f,0f,0f,0.813f,0f,0f,0f,-0.0184f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9996f,0.0279f,0.0009f,-0.3125f,0.0279f,0.9991f,0.0326f,1.375f,0f,0.0326f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9996f,-0.0279f,0.0009f,0.3125f,-0.0279f,0.9991f,-0.0326f,1.375f,0f,-0.0326f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.32995199091396105,"py":0.750576661231435,"pz":-0.020394166181949575,"ry":0.05226080260800359,"rx":1.8692012011996026}}}