# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.326f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0178f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.326f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0178f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.326f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0178f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.326f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0178f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.326f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0178f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9997f,0.024f,0.0008f,-0.3125f,0.024f,0.9992f,0.0316f,1.375f,0f,0.0316f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9997f,-0.024f,0.0008f,0.3125f,-0.024f,0.9992f,-0.0316f,1.375f,0f,-0.0316f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3274997465579844,"py":0.7504927475825405,"pz":-0.01976611446874942,"ry":0.043531370050487794,"rx":1.8118033913151443}}}