# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3239f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0171f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3239f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0171f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3239f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0171f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3239f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0171f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3239f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0171f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9998f,0.0203f,0.0006f,-0.3125f,0.0203f,0.9993f,0.0304f,1.375f,0f,0.0304f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9998f,-0.0203f,0.0006f,0.3125f,-0.0203f,0.9993f,-0.0304f,1.375f,0f,-0.0304f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3252128213990162,"py":0.7504186713522811,"pz":-0.0190144176015688,"ry":0.0354886655090354,"rx":1.7430212777713372}}}