# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3221f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0163f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3221f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0163f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3221f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0163f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3221f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0163f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3221f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0163f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9999f,0.017f,0.0005f,-0.3125f,0.017f,0.9994f,0.029f,1.375f,0f,0.029f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9999f,-0.017f,0.0005f,0.3125f,-0.017f,0.9994f,-0.029f,1.375f,0f,-0.029f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.32311243397774975,"py":0.7503536508644422,"pz":-0.018147031621911468,"ry":0.028271538602695045,"rx":1.6635910105995442}}}