# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3203f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0155f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3203f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0155f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3203f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0155f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3203f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0155f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3203f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0155f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9999f,0.0139f,0.0004f,-0.3125f,0.014f,0.9995f,0.0275f,1.375f,0f,0.0275f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9999f,-0.0139f,0.0004f,0.3125f,-0.014f,0.9995f,-0.0275f,1.375f,0f,-0.0275f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.32121799699593234,"py":0.7502967908410424,"pz":-0.017172565180502895,"ry":0.02197568662668914,"rx":1.5743096262802678}}}