# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3188f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3188f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3188f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3188f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3188f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9999f,0.0113f,0.0003f,-0.3125f,0.0113f,0.9996f,0.0258f,1.375f,0f,0.0258f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9999f,-0.0113f,0.0003f,0.3125f,-0.0113f,0.9996f,-0.0258f,1.375f,0f,-0.0258f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3195469396102051,"py":0.7502471500443342,"pz":-0.016100220942688488,"ry":0.01665264649193432,"rx":1.4760289093433412}}}