# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3176f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3176f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3176f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3176f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3176f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.009f,0.0002f,-0.3125f,0.009f,0.9997f,0.0239f,1.375f,0f,0.0239f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.009f,0.0002f,0.3125f,-0.009f,0.9997f,-0.0239f,1.375f,0f,-0.0239f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.31811454846286646,"py":0.7502038082688829,"pz":-0.01493973372758948,"ry":0.012310296164969259,"rx":1.3696490513631947}}}