# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3157f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3157f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3157f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3157f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3157f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0056f,0.0001f,-0.3125f,0.0056f,0.9998f,0.0198f,1.375f,0f,0.0198f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0056f,0.0001f,0.3125f,-0.0056f,0.9998f,-0.0198f,1.375f,0f,-0.0198f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3160153871080117,"py":0.750132819981705,"pz":-0.012395539095359278,"ry":0.006393991154482137,"rx":1.1363958426310334}}}