# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3672f,0f,0f,0f,0.8152f,0f,0f,0f,-0.0059f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3672f,0f,0f,0f,0.8152f,0f,0f,0f,-0.0059f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3672f,0f,0f,0f,0.8152f,0f,0f,0f,-0.0059f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3672f,0f,0f,0f,0.8152f,0f,0f,0f,-0.0059f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3672f,0f,0f,0f,0.8152f,0f,0f,0f,-0.0059f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9953f,0.0972f,0.001f,-0.3125f,0.0972f,0.9952f,0.0104f,1.375f,0f,0.0104f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9953f,-0.0972f,0.001f,0.3125f,-0.0972f,0.9952f,-0.0104f,1.375f,0f,-0.0104f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.37327366071055673,"py":0.7529958773884763,"pz":-0.0065141091568017085,"ry":0.05807377500767075,"rx":0.594350006123656}}}