# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3151f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3151f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3151f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3151f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3151f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0046f,0.0001f,-0.3125f,0.0046f,0.9998f,0.0177f,1.375f,0f,0.0177f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0046f,0.0001f,0.3125f,-0.0046f,0.9998f,-0.0177f,1.375f,0f,-0.0177f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3153673355200869,"py":0.7501039740800293,"pz":-0.011033366505402773,"ry":0.004641779666741286,"rx":1.011506429164356}}}