# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3147f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0087f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3147f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0087f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3147f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0087f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3147f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0087f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3147f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0087f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.004f,0.0001f,-0.3125f,0.004f,0.9999f,0.0154f,1.375f,0f,0.0154f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.004f,0.0001f,0.3125f,-0.004f,0.9999f,-0.0154f,1.375f,0f,-0.0154f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3149952200150818,"py":0.7500791134940732,"pz":-0.009625979727943984,"ry":0.003523866246524676,"rx":0.8824726751517178}}}