# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3147f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0074f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3147f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0074f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3147f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0074f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3147f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0074f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3147f,0f,0f,0f,0.8126f,0f,0f,0f,-0.0074f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0038f,0.0001f,-0.3125f,0.0038f,0.9999f,0.0131f,1.375f,0f,0.0131f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0038f,0.0001f,0.3125f,-0.0038f,0.9999f,-0.0131f,1.375f,0f,-0.0131f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3149019717883401,"py":0.7500582104834199,"pz":-0.00818475701181967,"ry":0.0028841030642183796,"rx":0.7503391582384481}}}