# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3148f,0f,0f,0f,0.8125f,0f,0f,0f,-0.006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3148f,0f,0f,0f,0.8125f,0f,0f,0f,-0.006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3148f,0f,0f,0f,0.8125f,0f,0f,0f,-0.006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3148f,0f,0f,0f,0.8125f,0f,0f,0f,-0.006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3148f,0f,0f,0f,0.8125f,0f,0f,0f,-0.006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0041f,0f,-0.3125f,0.0041f,0.9999f,0.0108f,1.375f,0f,0.0108f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0041f,0f,0.3125f,-0.0041f,0.9999f,-0.0108f,1.375f,0f,-0.0108f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3150878829538159,"py":0.7500414985988663,"pz":-0.006721189497885633,"ry":0.0025515471319863536,"rx":0.616159860252096}}}