# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3159f,0f,0f,0f,0.8125f,0f,0f,0f,-0.0034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3159f,0f,0f,0f,0.8125f,0f,0f,0f,-0.0034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3159f,0f,0f,0f,0.8125f,0f,0f,0f,-0.0034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3159f,0f,0f,0f,0.8125f,0f,0f,0f,-0.0034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3159f,0f,0f,0f,0.8125f,0f,0f,0f,-0.0034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0061f,0f,-0.3125f,0.0061f,1f,0.006f,1.375f,0f,0.006f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0061f,0f,0.3125f,-0.0061f,1f,-0.006f,1.375f,0f,-0.006f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.31628518109745096,"py":0.750022851551296,"pz":-0.0037731049529663102,"ry":0.0020949032669648204,"rx":0.34588854034324423}}}