# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3168f,0f,0f,0f,0.8125f,0f,0f,0f,-0.0021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3168f,0f,0f,0f,0.8125f,0f,0f,0f,-0.0021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3168f,0f,0f,0f,0.8125f,0f,0f,0f,-0.0021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3168f,0f,0f,0f,0.8125f,0f,0f,0f,-0.0021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3168f,0f,0f,0f,0.8125f,0f,0f,0f,-0.0021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0077f,0f,-0.3125f,0.0077f,1f,0.0037f,1.375f,0f,0.0037f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0077f,0f,0.3125f,-0.0077f,1f,-0.0037f,1.375f,0f,-0.0037f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.31728407910585654,"py":0.7500225846493445,"pz":-0.002311468953540333,"ry":0.0016220153304686846,"rx":0.21189413986508956}}}