# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3179f,0f,0f,0f,0.8125f,0f,0f,0f,-0.0008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3179f,0f,0f,0f,0.8125f,0f,0f,0f,-0.0008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3179f,0f,0f,0f,0.8125f,0f,0f,0f,-0.0008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3179f,0f,0f,0f,0.8125f,0f,0f,0f,-0.0008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3179f,0f,0f,0f,0.8125f,0f,0f,0f,-0.0008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0097f,0f,-0.3125f,0.0097f,1f,0.0014f,1.375f,0f,0.0014f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0097f,0f,0.3125f,-0.0097f,1f,-0.0014f,1.375f,0f,-0.0014f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3185372799830752,"py":0.7500297695572606,"pz":-0.0008731040919002919,"ry":0.0007731625074427484,"rx":0.08003657897013122}}}