# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3193f,0f,0f,0f,0.8125f,0f,0f,0f,0.0005f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3193f,0f,0f,0f,0.8125f,0f,0f,0f,0.0005f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3193f,0f,0f,0f,0.8125f,0f,0f,0f,0.0005f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3193f,0f,0f,0f,0.8125f,0f,0f,0f,0.0005f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3193f,0f,0f,0f,0.8125f,0f,0f,0f,0.0005f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9999f,0.0121f,0f,-0.3125f,0.0121f,0.9999f,-0.0008f,1.375f,0f,-0.0008f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9999f,-0.0121f,0f,0.3125f,-0.0121f,0.9999f,0.0008f,1.375f,0f,0.0008f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3200323660267161,"py":0.7500456164954689,"pz":0.0005310372030199816,"ry":359.9994132956952,"rx":-0.04867837510646559}}}