# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3208f,0f,0f,0f,0.8126f,0f,0f,0f,0.0017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3208f,0f,0f,0f,0.8126f,0f,0f,0f,0.0017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3208f,0f,0f,0f,0.8126f,0f,0f,0f,0.0017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3208f,0f,0f,0f,0.8126f,0f,0f,0f,0.0017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3208f,0f,0f,0f,0.8126f,0f,0f,0f,0.0017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9999f,0.0148f,0f,-0.3125f,0.0148f,0.9999f,-0.003f,1.375f,0f,-0.003f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9999f,-0.0148f,0f,0.3125f,-0.0148f,0.9999f,0.003f,1.375f,0f,0.003f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3217546412117048,"py":0.7500713814442408,"pz":0.0018903243195492483,"ry":359.99743396557494,"rx":-0.17327343356865613}}}