# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3226f,0f,0f,0f,0.8126f,0f,0f,0f,0.0029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3226f,0f,0f,0f,0.8126f,0f,0f,0f,0.0029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3226f,0f,0f,0f,0.8126f,0f,0f,0f,0.0029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3226f,0f,0f,0f,0.8126f,0f,0f,0f,0.0029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3226f,0f,0f,0f,0.8126f,0f,0f,0f,0.0029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9998f,0.0179f,-0.0001f,-0.3125f,0.0179f,0.9998f,-0.0051f,1.375f,0f,-0.0051f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9998f,-0.0179f,-0.0001f,0.3125f,-0.0179f,0.9998f,0.0051f,1.375f,0f,0.0051f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.32368727163221206,"py":0.7501082973635376,"pz":0.0031945155391796707,"ry":359.9947579262034,"rx":-0.29280596792117664}}}