# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3245f,0f,0f,0f,0.8126f,0f,0f,0f,0.004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3245f,0f,0f,0f,0.8126f,0f,0f,0f,0.004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3245f,0f,0f,0f,0.8126f,0f,0f,0f,0.004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3245f,0f,0f,0f,0.8126f,0f,0f,0f,0.004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3245f,0f,0f,0f,0.8126f,0f,0f,0f,0.004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9998f,0.0213f,-0.0002f,-0.3125f,0.0213f,0.9997f,-0.0071f,1.375f,0f,-0.0071f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9998f,-0.0213f,-0.0002f,0.3125f,-0.0213f,0.9997f,0.0071f,1.375f,0f,0.0071f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3258114463978652,"py":0.7501575025548965,"pz":0.004433822432466839,"ry":359.9913425897995,"rx":-0.406374102470293}}}