# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3287f,0f,0f,0f,0.8128f,0f,0f,0f,0.006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3287f,0f,0f,0f,0.8128f,0f,0f,0f,0.006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3287f,0f,0f,0f,0.8128f,0f,0f,0f,0.006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3287f,0f,0f,0f,0.8128f,0f,0f,0f,0.006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3287f,0f,0f,0f,0.8128f,0f,0f,0f,0.006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9996f,0.0289f,-0.0003f,-0.3125f,0.0289f,0.9995f,-0.0107f,1.375f,0f,-0.0107f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9996f,-0.0289f,-0.0003f,0.3125f,-0.0289f,0.9995f,0.0107f,1.375f,0f,0.0107f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3305503970941119,"py":0.7502964351611994,"pz":0.006681260542693886,"ry":359.9823087962334,"rx":-0.612248981158998}}}