# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3311f,0f,0f,0f,0.8128f,0f,0f,0f,0.0069f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3311f,0f,0f,0f,0.8128f,0f,0f,0f,0.0069f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3311f,0f,0f,0f,0.8128f,0f,0f,0f,0.0069f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3311f,0f,0f,0f,0.8128f,0f,0f,0f,0.0069f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3311f,0f,0f,0f,0.8128f,0f,0f,0f,0.0069f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9995f,0.033f,-0.0004f,-0.3125f,0.033f,0.9994f,-0.0123f,1.375f,0f,-0.0123f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9995f,-0.033f,-0.0004f,0.3125f,-0.033f,0.9994f,0.0123f,1.375f,0f,0.0123f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.33311936982718104,"py":0.750387341984648,"pz":0.0076726159115919484,"ry":359.9767915105193,"rx":-0.7030083147992892}}}