# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3384f,0f,0f,0f,0.8132f,0f,0f,0f,0.009f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3384f,0f,0f,0f,0.8132f,0f,0f,0f,0.009f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3384f,0f,0f,0f,0.8132f,0f,0f,0f,0.009f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3384f,0f,0f,0f,0.8132f,0f,0f,0f,0.009f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3384f,0f,0f,0f,0.8132f,0f,0f,0f,0.009f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9989f,0.0461f,-0.0007f,-0.3125f,0.0461f,0.9988f,-0.016f,1.375f,0f,-0.016f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9989f,-0.0461f,-0.0007f,0.3125f,-0.0461f,0.9988f,0.016f,1.375f,0f,0.016f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3413251381645899,"py":0.7507456485020119,"pz":0.01003075498746704,"ry":359.9575791450426,"rx":-0.9186124856640516}}}