# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3435f,0f,0f,0f,0.8134f,0f,0f,0f,0.0099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3435f,0f,0f,0f,0.8134f,0f,0f,0f,0.0099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3435f,0f,0f,0f,0.8134f,0f,0f,0f,0.0099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3435f,0f,0f,0f,0.8134f,0f,0f,0f,0.0099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3435f,0f,0f,0f,0.8134f,0f,0f,0f,0.0099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9985f,0.0551f,-0.001f,-0.3125f,0.0551f,0.9983f,-0.0176f,1.375f,0f,-0.0177f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9985f,-0.0551f,-0.001f,0.3125f,-0.0551f,0.9983f,0.0176f,1.375f,0f,0.0177f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.346947550786883,"py":0.7510475592841769,"pz":0.011032586711752581,"ry":359.94423862098546,"rx":-1.0099074978731304}}}