# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.365f,0f,0f,0f,0.815f,0f,0f,0f,-0.0093f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.365f,0f,0f,0f,0.815f,0f,0f,0f,-0.0093f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.365f,0f,0f,0f,0.815f,0f,0f,0f,-0.0093f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.365f,0f,0f,0f,0.815f,0f,0f,0f,-0.0093f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.365f,0f,0f,0f,0.815f,0f,0f,0f,-0.0093f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9956f,0.0933f,0.0015f,-0.3125f,0.0933f,0.9955f,0.0165f,1.375f,0f,0.0166f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9956f,-0.0933f,0.0015f,0.3125f,-0.0933f,0.9955f,-0.0165f,1.375f,0f,-0.0166f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3708077422249226,"py":0.7528118602755811,"pz":-0.010350168254621372,"ry":0.0885431575399025,"rx":0.9447371085740116}}}