# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.346f,0f,0f,0f,0.8136f,0f,0f,0f,0.0102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.346f,0f,0f,0f,0.8136f,0f,0f,0f,0.0102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.346f,0f,0f,0f,0.8136f,0f,0f,0f,0.0102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.346f,0f,0f,0f,0.8136f,0f,0f,0f,0.0102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.346f,0f,0f,0f,0.8136f,0f,0f,0f,0.0102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9982f,0.0596f,-0.0011f,-0.3125f,0.0596f,0.9981f,-0.0181f,1.375f,0f,-0.0182f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9982f,-0.0596f,-0.0011f,0.3125f,-0.0596f,0.9981f,0.0181f,1.375f,0f,0.0182f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.34972373673491236,"py":0.7512127129089222,"pz":0.011349620568250143,"ry":359.93801209237967,"rx":-1.0386658822758046}}}