# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3484f,0f,0f,0f,0.8137f,0f,0f,0f,0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3484f,0f,0f,0f,0.8137f,0f,0f,0f,0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3484f,0f,0f,0f,0.8137f,0f,0f,0f,0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3484f,0f,0f,0f,0.8137f,0f,0f,0f,0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3484f,0f,0f,0f,0.8137f,0f,0f,0f,0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.998f,0.0639f,-0.0012f,-0.3125f,0.0639f,0.9978f,-0.0184f,1.375f,0f,-0.0185f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.998f,-0.0639f,-0.0012f,0.3125f,-0.0639f,0.9978f,0.0184f,1.375f,0f,0.0185f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.35244106151399235,"py":0.7513843081659941,"pz":0.0115403857617387,"ry":359.9323682819841,"rx":-1.0558411556459482}}}