# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3508f,0f,0f,0f,0.8139f,0f,0f,0f,0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3508f,0f,0f,0f,0.8139f,0f,0f,0f,0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3508f,0f,0f,0f,0.8139f,0f,0f,0f,0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3508f,0f,0f,0f,0.8139f,0f,0f,0f,0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3508f,0f,0f,0f,0.8139f,0f,0f,0f,0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9977f,0.0681f,-0.0013f,-0.3125f,0.0681f,0.9975f,-0.0185f,1.375f,0f,-0.0186f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9977f,-0.0681f,-0.0013f,0.3125f,-0.0681f,0.9975f,0.0185f,1.375f,0f,0.0186f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3550735537032703,"py":0.7515596601094718,"pz":0.011603237576531348,"ry":359.92751783349036,"rx":-1.0612956238859743}}}