# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3531f,0f,0f,0f,0.8141f,0f,0f,0f,0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3531f,0f,0f,0f,0.8141f,0f,0f,0f,0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3531f,0f,0f,0f,0.8141f,0f,0f,0f,0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3531f,0f,0f,0f,0.8141f,0f,0f,0f,0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3531f,0f,0f,0f,0.8141f,0f,0f,0f,0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9974f,0.0722f,-0.0013f,-0.3125f,0.0722f,0.9972f,-0.0184f,1.375f,0f,-0.0185f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9974f,-0.0722f,-0.0013f,0.3125f,-0.0722f,0.9972f,0.0184f,1.375f,0f,0.0185f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.35759606430158664,"py":0.7517358244580677,"pz":0.01153743778065798,"ry":359.9236589071738,"rx":-1.0549762535400993}}}