# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3552f,0f,0f,0f,0.8142f,0f,0f,0f,0.0102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3552f,0f,0f,0f,0.8142f,0f,0f,0f,0.0102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3552f,0f,0f,0f,0.8142f,0f,0f,0f,0.0102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3552f,0f,0f,0f,0.8142f,0f,0f,0f,0.0102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3552f,0f,0f,0f,0.8142f,0f,0f,0f,0.0102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9971f,0.076f,-0.0014f,-0.3125f,0.076f,0.9969f,-0.0181f,1.375f,0f,-0.0181f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9971f,-0.076f,-0.0014f,0.3125f,-0.076f,0.9969f,0.0181f,1.375f,0f,0.0181f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3599844989679006,"py":0.7519096734165072,"pz":0.011343159870320864,"ry":359.92097012221524,"rx":-1.0369143966918004}}}