# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3572f,0f,0f,0f,0.8144f,0f,0f,0f,0.0099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3572f,0f,0f,0f,0.8144f,0f,0f,0f,0.0099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3572f,0f,0f,0f,0.8144f,0f,0f,0f,0.0099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3572f,0f,0f,0f,0.8144f,0f,0f,0f,0.0099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3572f,0f,0f,0f,0.8144f,0f,0f,0f,0.0099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9968f,0.0795f,-0.0014f,-0.3125f,0.0796f,0.9967f,-0.0176f,1.375f,0f,-0.0176f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9968f,-0.0795f,-0.0014f,0.3125f,-0.0796f,0.9967f,0.0176f,1.375f,0f,0.0176f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.36221603913056993,"py":0.7520779806138425,"pz":0.011021488875794211,"ry":359.91960404939493,"rx":-1.007224899100438}}}