# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3591f,0f,0f,0f,0.8145f,0f,0f,0f,0.0095f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3591f,0f,0f,0f,0.8145f,0f,0f,0f,0.0095f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3591f,0f,0f,0f,0.8145f,0f,0f,0f,0.0095f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3591f,0f,0f,0f,0.8145f,0f,0f,0f,0.0095f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3591f,0f,0f,0f,0.8145f,0f,0f,0f,0.0095f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9966f,0.0828f,-0.0014f,-0.3125f,0.0828f,0.9964f,-0.0169f,1.375f,0f,-0.0169f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9966f,-0.0828f,-0.0014f,0.3125f,-0.0828f,0.9964f,0.0169f,1.375f,0f,0.0169f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.36426935015208506,"py":0.7522375122754129,"pz":0.010574415724488317,"ry":359.9196814714232,"rx":-0.9661046467572582}}}