# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3622f,0f,0f,0f,0.8148f,0f,0f,0f,0.0084f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3622f,0f,0f,0f,0.8148f,0f,0f,0f,0.0084f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3622f,0f,0f,0f,0.8148f,0f,0f,0f,0.0084f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3622f,0f,0f,0f,0.8148f,0f,0f,0f,0.0084f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3622f,0f,0f,0f,0.8148f,0f,0f,0f,0.0084f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9961f,0.0884f,-0.0013f,-0.3125f,0.0884f,0.996f,-0.0148f,1.375f,0f,-0.0149f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9961f,-0.0884f,-0.0013f,0.3125f,-0.0884f,0.996f,0.0148f,1.375f,0f,0.0149f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3677645116720557,"py":0.7525178421286046,"pz":0.00931648439167914,"ry":359.92446343098186,"rx":-0.8507574887000917}}}