# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3635f,0f,0f,0f,0.8149f,0f,0f,0f,0.0077f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3635f,0f,0f,0f,0.8149f,0f,0f,0f,0.0077f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3635f,0f,0f,0f,0.8149f,0f,0f,0f,0.0077f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3635f,0f,0f,0f,0.8149f,0f,0f,0f,0.0077f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3635f,0f,0f,0f,0.8149f,0f,0f,0f,0.0077f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9959f,0.0907f,-0.0012f,-0.3125f,0.0907f,0.9958f,-0.0136f,1.375f,0f,-0.0136f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9959f,-0.0907f,-0.0012f,0.3125f,-0.0907f,0.9958f,0.0136f,1.375f,0f,0.0136f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.36917277425622086,"py":0.7526329794466552,"pz":0.00851401113788155,"ry":359.9292133005338,"rx":-0.7773149224888045}}}