# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3635f,0f,0f,0f,0.8149f,0f,0f,0f,-0.0109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3635f,0f,0f,0f,0.8149f,0f,0f,0f,-0.0109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3635f,0f,0f,0f,0.8149f,0f,0f,0f,-0.0109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3635f,0f,0f,0f,0.8149f,0f,0f,0f,-0.0109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3635f,0f,0f,0f,0.8149f,0f,0f,0f,-0.0109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9959f,0.0907f,0.0018f,-0.3125f,0.0907f,0.9957f,0.0193f,1.375f,0f,0.0193f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9959f,-0.0907f,0.0018f,0.3125f,-0.0907f,0.9957f,-0.0193f,1.375f,0f,-0.0193f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3691944983767931,"py":0.7526941093813847,"pz":-0.01208769436972123,"ry":0.10055623788554158,"rx":1.10361621841629}}}