# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3646f,0f,0f,0f,0.815f,0f,0f,0f,0.0068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3646f,0f,0f,0f,0.815f,0f,0f,0f,0.0068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3646f,0f,0f,0f,0.815f,0f,0f,0f,0.0068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3646f,0f,0f,0f,0.815f,0f,0f,0f,0.0068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3646f,0f,0f,0f,0.815f,0f,0f,0f,0.0068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9957f,0.0925f,-0.0011f,-0.3125f,0.0925f,0.9956f,-0.0121f,1.375f,0f,-0.0122f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9957f,-0.0925f,-0.0011f,0.3125f,-0.0925f,0.9956f,0.0121f,1.375f,0f,0.0122f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.370335934805111,"py":0.7527281934609508,"pz":0.007602856821423618,"ry":359.9354938301433,"rx":-0.6940045042893398}}}