# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3659f,0f,0f,0f,0.8151f,0f,0f,0f,0.0049f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3659f,0f,0f,0f,0.8151f,0f,0f,0f,0.0049f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3659f,0f,0f,0f,0.8151f,0f,0f,0f,0.0049f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3659f,0f,0f,0f,0.8151f,0f,0f,0f,0.0049f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3659f,0f,0f,0f,0.8151f,0f,0f,0f,0.0049f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9955f,0.095f,-0.0008f,-0.3125f,0.095f,0.9954f,-0.0087f,1.375f,0f,-0.0088f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9955f,-0.095f,-0.0008f,0.3125f,-0.095f,0.9954f,0.0087f,1.375f,0f,0.0088f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.37188394942546626,"py":0.7528516950658477,"pz":0.005480257128530055,"ry":359.95226181506325,"rx":-0.5001262693281738}}}