# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3663f,0f,0f,0f,0.8151f,0f,0f,0f,0.0039f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3663f,0f,0f,0f,0.8151f,0f,0f,0f,0.0039f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3663f,0f,0f,0f,0.8151f,0f,0f,0f,0.0039f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3663f,0f,0f,0f,0.8151f,0f,0f,0f,0.0039f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3663f,0f,0f,0f,0.8151f,0f,0f,0f,0.0039f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9954f,0.0956f,-0.0007f,-0.3125f,0.0956f,0.9954f,-0.0068f,1.375f,0f,-0.0069f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9954f,-0.0956f,-0.0007f,0.3125f,-0.0956f,0.9954f,0.0068f,1.375f,0f,0.0069f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3722533492246796,"py":0.7528776740212642,"pz":0.004283547039668129,"ry":359.9624552921364,"rx":-0.39089084094441495}}}