# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3662f,0f,0f,0f,0.8151f,0f,0f,0f,0.0015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3662f,0f,0f,0f,0.8151f,0f,0f,0f,0.0015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3662f,0f,0f,0f,0.8151f,0f,0f,0f,0.0015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3662f,0f,0f,0f,0.8151f,0f,0f,0f,0.0015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3662f,0f,0f,0f,0.8151f,0f,0f,0f,0.0015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9954f,0.0955f,-0.0003f,-0.3125f,0.0955f,0.9954f,-0.0026f,1.375f,0f,-0.0027f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9954f,-0.0955f,-0.0003f,0.3125f,-0.0955f,0.9954f,0.0026f,1.375f,0f,0.0027f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3721631615040287,"py":0.7528564897023282,"pz":0.0016612506839543638,"ry":359.98546191873993,"rx":-0.15159692307281122}}}