# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3658f,0f,0f,0f,0.815f,0f,0f,0f,0.0002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3658f,0f,0f,0f,0.815f,0f,0f,0f,0.0002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3658f,0f,0f,0f,0.815f,0f,0f,0f,0.0002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3658f,0f,0f,0f,0.815f,0f,0f,0f,0.0002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3658f,0f,0f,0f,0.815f,0f,0f,0f,0.0002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9955f,0.0947f,0f,-0.3125f,0.0947f,0.9955f,-0.0004f,1.375f,0f,-0.0004f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9955f,-0.0947f,0f,0.3125f,-0.0947f,0.9955f,0.0004f,1.375f,0f,0.0004f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3717033807836904,"py":0.752810402650579,"pz":0.00025427140352666855,"ry":359.99779196121693,"rx":-0.02320507153027873}}}