# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3651f,0f,0f,0f,0.815f,0f,0f,0f,-0.0011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3651f,0f,0f,0f,0.815f,0f,0f,0f,-0.0011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3651f,0f,0f,0f,0.815f,0f,0f,0f,-0.0011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3651f,0f,0f,0f,0.815f,0f,0f,0f,-0.0011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3651f,0f,0f,0f,0.815f,0f,0f,0f,-0.0011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9956f,0.0936f,0.0002f,-0.3125f,0.0936f,0.9956f,0.0019f,1.375f,0f,0.0019f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9956f,-0.0936f,0.0002f,0.3125f,-0.0936f,0.9956f,-0.0019f,1.375f,0f,-0.0019f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3709713261672673,"py":0.7527422912711469,"pz":-0.001203305347312942,"ry":0.010320078327424653,"rx":0.1098271719662237}}}