# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3642f,0f,0f,0f,0.8149f,0f,0f,0f,-0.0024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3642f,0f,0f,0f,0.8149f,0f,0f,0f,-0.0024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3642f,0f,0f,0f,0.8149f,0f,0f,0f,-0.0024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3642f,0f,0f,0f,0.8149f,0f,0f,0f,-0.0024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3642f,0f,0f,0f,0.8149f,0f,0f,0f,-0.0024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9958f,0.092f,0.0004f,-0.3125f,0.092f,0.9958f,0.0043f,1.375f,0f,0.0043f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9958f,-0.092f,0.0004f,0.3125f,-0.092f,0.9958f,-0.0043f,1.375f,0f,-0.0043f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.36997334235193347,"py":0.7526540191790954,"pz":-0.002700939644564013,"ry":0.022769422683097673,"rx":0.24655553813184375}}}