# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3619f,0f,0f,0f,0.8148f,0f,0f,0f,-0.0123f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3619f,0f,0f,0f,0.8148f,0f,0f,0f,-0.0123f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3619f,0f,0f,0f,0.8148f,0f,0f,0f,-0.0123f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3619f,0f,0f,0f,0.8148f,0f,0f,0f,-0.0123f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3619f,0f,0f,0f,0.8148f,0f,0f,0f,-0.0123f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9961f,0.0878f,0.0019f,-0.3125f,0.0878f,0.9959f,0.0218f,1.375f,0f,0.0219f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9961f,-0.0878f,0.0019f,0.3125f,-0.0878f,0.9959f,-0.0218f,1.375f,0f,-0.0219f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3673487708077175,"py":0.7525619867037857,"pz":-0.013694230345084771,"ry":0.11022373843451305,"rx":1.2506480073386006}}}