# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3602f,0f,0f,0f,0.8146f,0f,0f,0f,-0.0066f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3602f,0f,0f,0f,0.8146f,0f,0f,0f,-0.0066f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3602f,0f,0f,0f,0.8146f,0f,0f,0f,-0.0066f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3602f,0f,0f,0f,0.8146f,0f,0f,0f,-0.0066f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3602f,0f,0f,0f,0.8146f,0f,0f,0f,-0.0066f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9964f,0.0848f,0.001f,-0.3125f,0.0848f,0.9963f,0.0117f,1.375f,0f,0.0117f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9964f,-0.0848f,0.001f,0.3125f,-0.0848f,0.9963f,-0.0117f,1.375f,0f,-0.0117f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3654844780365406,"py":0.7522929970433553,"pz":-0.00732349342517652,"ry":0.056923165698094635,"rx":0.6689664346543444}}}