# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3584f,0f,0f,0f,0.8144f,0f,0f,0f,-0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3584f,0f,0f,0f,0.8144f,0f,0f,0f,-0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3584f,0f,0f,0f,0.8144f,0f,0f,0f,-0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3584f,0f,0f,0f,0.8144f,0f,0f,0f,-0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3584f,0f,0f,0f,0.8144f,0f,0f,0f,-0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9967f,0.0817f,0.0012f,-0.3125f,0.0817f,0.9966f,0.0141f,1.375f,0f,0.0142f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9967f,-0.0817f,0.0012f,0.3125f,-0.0817f,0.9966f,-0.0141f,1.375f,0f,-0.0142f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.363535237391639,"py":0.7521503082044648,"pz":-0.008869384115367713,"ry":0.06640694103521128,"rx":0.810396451103499}}}