# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3522f,0f,0f,0f,0.814f,0f,0f,0f,-0.012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3522f,0f,0f,0f,0.814f,0f,0f,0f,-0.012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3522f,0f,0f,0f,0.814f,0f,0f,0f,-0.012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3522f,0f,0f,0f,0.814f,0f,0f,0f,-0.012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3522f,0f,0f,0f,0.814f,0f,0f,0f,-0.012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9975f,0.0705f,0.0015f,-0.3125f,0.0705f,0.9973f,0.0213f,1.375f,0f,0.0214f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9975f,-0.0705f,0.0015f,0.3125f,-0.0705f,0.9973f,-0.0213f,1.375f,0f,-0.0214f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.35657896690823415,"py":0.7516994302651585,"pz":-0.013358309942683708,"ry":0.08640594620379716,"rx":1.2216414599278915}}}