# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3474f,0f,0f,0f,0.8138f,0f,0f,0f,-0.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3474f,0f,0f,0f,0.8138f,0f,0f,0f,-0.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3474f,0f,0f,0f,0.8138f,0f,0f,0f,-0.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3474f,0f,0f,0f,0.8138f,0f,0f,0f,-0.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3474f,0f,0f,0f,0.8138f,0f,0f,0f,-0.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9981f,0.062f,0.0016f,-0.3125f,0.062f,0.9977f,0.0257f,1.375f,0f,0.0258f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9981f,-0.062f,0.0016f,0.3125f,-0.062f,0.9977f,-0.0257f,1.375f,0f,-0.0258f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3512372477966954,"py":0.7514096861629566,"pz":-0.01611043518204954,"ry":0.09159819571286221,"rx":1.4742172193749792}}}