# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3448f,0f,0f,0f,0.8136f,0f,0f,0f,-0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3448f,0f,0f,0f,0.8136f,0f,0f,0f,-0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3448f,0f,0f,0f,0.8136f,0f,0f,0f,-0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3448f,0f,0f,0f,0.8136f,0f,0f,0f,-0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3448f,0f,0f,0f,0.8136f,0f,0f,0f,-0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9983f,0.0575f,0.0016f,-0.3125f,0.0575f,0.998f,0.0278f,1.375f,0f,0.0278f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9983f,-0.0575f,0.0016f,0.3125f,-0.0575f,0.998f,-0.0278f,1.375f,0f,-0.0278f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.34842846018854196,"py":0.7512756448108928,"pz":-0.017380290343166203,"ry":0.09166295074885511,"rx":1.5908752289994084}}}