# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3423f,0f,0f,0f,0.8135f,0f,0f,0f,-0.0167f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3423f,0f,0f,0f,0.8135f,0f,0f,0f,-0.0167f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3423f,0f,0f,0f,0.8135f,0f,0f,0f,-0.0167f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3423f,0f,0f,0f,0.8135f,0f,0f,0f,-0.0167f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3423f,0f,0f,0f,0.8135f,0f,0f,0f,-0.0167f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9986f,0.0529f,0.0016f,-0.3125f,0.0529f,0.9982f,0.0297f,1.375f,0f,0.0297f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9986f,-0.0529f,0.0016f,0.3125f,-0.0529f,0.9982f,-0.0297f,1.375f,0f,-0.0297f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.34556278773933474,"py":0.7511513024815513,"pz":-0.01856487736126321,"ry":0.09011086266366419,"rx":1.6997667829100385}}}