# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.36f,0f,0f,0f,0.8147f,0f,0f,0f,-0.0136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.36f,0f,0f,0f,0.8147f,0f,0f,0f,-0.0136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.36f,0f,0f,0f,0.8147f,0f,0f,0f,-0.0136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.36f,0f,0f,0f,0.8147f,0f,0f,0f,-0.0136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.36f,0f,0f,0f,0.8147f,0f,0f,0f,-0.0136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9964f,0.0845f,0.002f,-0.3125f,0.0845f,0.9961f,0.0242f,1.375f,0f,0.0243f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9964f,-0.0845f,0.002f,0.3125f,-0.0845f,0.9961f,-0.0242f,1.375f,0f,-0.0243f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3652889797745572,"py":0.7524179500525877,"pz":-0.015162938291743769,"ry":0.11747469290716595,"rx":1.3852007397145085}}}