# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3397f,0f,0f,0f,0.8134f,0f,0f,0f,-0.0177f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3397f,0f,0f,0f,0.8134f,0f,0f,0f,-0.0177f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3397f,0f,0f,0f,0.8134f,0f,0f,0f,-0.0177f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3397f,0f,0f,0f,0.8134f,0f,0f,0f,-0.0177f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3397f,0f,0f,0f,0.8134f,0f,0f,0f,-0.0177f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9988f,0.0483f,0.0015f,-0.3125f,0.0483f,0.9983f,0.0314f,1.375f,0f,0.0314f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9988f,-0.0483f,0.0015f,0.3125f,-0.0483f,0.9983f,-0.0314f,1.375f,0f,-0.0314f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.34266737042538736,"py":0.7510379371887435,"pz":-0.01965385290315606,"ry":0.08705166665478714,"rx":1.7999264294401407}}}