# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.337f,0f,0f,0f,0.8133f,0f,0f,0f,-0.0186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.337f,0f,0f,0f,0.8133f,0f,0f,0f,-0.0186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.337f,0f,0f,0f,0.8133f,0f,0f,0f,-0.0186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.337f,0f,0f,0f,0.8133f,0f,0f,0f,-0.0186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.337f,0f,0f,0f,0.8133f,0f,0f,0f,-0.0186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.999f,0.0436f,0.0014f,-0.3125f,0.0437f,0.9985f,0.033f,1.375f,0f,0.033f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.999f,-0.0436f,0.0014f,0.3125f,-0.0437f,0.9985f,-0.033f,1.375f,0f,-0.033f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3397697133065021,"py":0.7509363316511655,"pz":-0.020637358919616888,"ry":0.08263627991371436,"rx":1.8904330471117807}}}