# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3345f,0f,0f,0f,0.8133f,0f,0f,0f,-0.0194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3345f,0f,0f,0f,0.8133f,0f,0f,0f,-0.0194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3345f,0f,0f,0f,0.8133f,0f,0f,0f,-0.0194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3345f,0f,0f,0f,0.8133f,0f,0f,0f,-0.0194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3345f,0f,0f,0f,0.8133f,0f,0f,0f,-0.0194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9992f,0.039f,0.0013f,-0.3125f,0.0391f,0.9986f,0.0344f,1.375f,0f,0.0344f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9992f,-0.039f,0.0013f,0.3125f,-0.0391f,0.9986f,-0.0344f,1.375f,0f,-0.0344f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.33689742596332345,"py":0.7508467705899928,"pz":-0.021506088054854485,"ry":0.0770517109569937,"rx":1.970416837120561}}}