# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3319f,0f,0f,0f,0.8132f,0f,0f,0f,-0.02f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3319f,0f,0f,0f,0.8132f,0f,0f,0f,-0.02f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3319f,0f,0f,0f,0.8132f,0f,0f,0f,-0.02f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3319f,0f,0f,0f,0.8132f,0f,0f,0f,-0.02f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3319f,0f,0f,0f,0.8132f,0f,0f,0f,-0.02f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9994f,0.0345f,0.0012f,-0.3125f,0.0345f,0.9988f,0.0356f,1.375f,0f,0.0356f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9994f,-0.0345f,0.0012f,0.3125f,-0.0345f,0.9988f,-0.0356f,1.375f,0f,-0.0356f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3340779608478476,"py":0.7507690577981196,"pz":-0.022251346103133448,"ry":0.0705147371435828,"rx":2.0390659344506394}}}