# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3295f,0f,0f,0f,0.8131f,0f,0f,0f,-0.0206f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3295f,0f,0f,0f,0.8131f,0f,0f,0f,-0.0206f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3295f,0f,0f,0f,0.8131f,0f,0f,0f,-0.0206f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3295f,0f,0f,0f,0.8131f,0f,0f,0f,-0.0206f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3295f,0f,0f,0f,0.8131f,0f,0f,0f,-0.0206f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9995f,0.0301f,0.0011f,-0.3125f,0.0302f,0.9989f,0.0366f,1.375f,0f,0.0366f,-0.9993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9995f,-0.0301f,0.0011f,0.3125f,-0.0302f,0.9989f,-0.0366f,1.375f,0f,-0.0366f,-0.9993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.33133835337474843,"py":0.7507025523575853,"pz":-0.02286511118045698,"ry":0.06326453610788008,"rx":2.0956325512004943}}}