# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3271f,0f,0f,0f,0.8131f,0f,0f,0f,-0.021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3271f,0f,0f,0f,0.8131f,0f,0f,0f,-0.021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3271f,0f,0f,0f,0.8131f,0f,0f,0f,-0.021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3271f,0f,0f,0f,0.8131f,0f,0f,0f,-0.021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3271f,0f,0f,0f,0.8131f,0f,0f,0f,-0.021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9997f,0.0259f,0.001f,-0.3125f,0.0259f,0.999f,0.0373f,1.375f,0f,0.0373f,-0.9993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9997f,-0.0259f,0.001f,0.3125f,-0.0259f,0.999f,-0.0373f,1.375f,0f,-0.0373f,-0.9993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.32870496648234704,"py":0.7506462226489282,"pz":-0.02334008930476231,"ry":0.05555449388648981,"rx":2.1394385816458823}}}