# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3248f,0f,0f,0f,0.813f,0f,0f,0f,-0.0213f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3248f,0f,0f,0f,0.813f,0f,0f,0f,-0.0213f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3248f,0f,0f,0f,0.813f,0f,0f,0f,-0.0213f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3248f,0f,0f,0f,0.813f,0f,0f,0f,-0.0213f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3248f,0f,0f,0f,0.813f,0f,0f,0f,-0.0213f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9998f,0.0219f,0.0008f,-0.3125f,0.0219f,0.999f,0.0379f,1.375f,0f,0.0379f,-0.9993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9998f,-0.0219f,0.0008f,0.3125f,-0.0219f,0.999f,-0.0379f,1.375f,0f,-0.0379f,-0.9993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.32620324223646124,"py":0.7505987161089045,"pz":-0.023669766102782343,"ry":0.04764344285143807,"rx":2.1698806174407625}}}