# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.358f,0f,0f,0f,0.8145f,0f,0f,0f,-0.0148f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.358f,0f,0f,0f,0.8145f,0f,0f,0f,-0.0148f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.358f,0f,0f,0f,0.8145f,0f,0f,0f,-0.0148f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.358f,0f,0f,0f,0.8145f,0f,0f,0f,-0.0148f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.358f,0f,0f,0f,0.8145f,0f,0f,0f,-0.0148f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9967f,0.0809f,0.0021f,-0.3125f,0.0809f,0.9964f,0.0263f,1.375f,0f,0.0264f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9967f,-0.0809f,0.0021f,0.3125f,-0.0809f,0.9964f,-0.0263f,1.375f,0f,-0.0264f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.36303545264231835,"py":0.7522646501556494,"pz":-0.016487937423165493,"ry":0.12230009019464205,"rx":1.5067239060221589}}}