# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3174f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0211f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3174f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0211f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3174f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0211f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3174f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0211f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3174f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0211f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0088f,0.0003f,-0.3125f,0.0088f,0.9993f,0.0375f,1.375f,0f,0.0375f,-0.9993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0088f,0.0003f,0.3125f,-0.0088f,0.9993f,-0.0375f,1.375f,0f,-0.0375f,-0.9993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3179765379195433,"py":0.7504635252015532,"pz":-0.023434999013120524,"ry":0.01885144505516223,"rx":2.14878353968029}}}