# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3161f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3161f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3161f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3161f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3161f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0063f,0.0002f,-0.3125f,0.0064f,0.9993f,0.0368f,1.375f,0f,0.0368f,-0.9993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0063f,0.0002f,0.3125f,-0.0064f,0.9993f,-0.0368f,1.375f,0f,-0.0368f,-0.9993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.31646649658901077,"py":0.7504348646008495,"pz":-0.0229708195032343,"ry":0.013382375397583246,"rx":2.106241499548476}}}