# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3149f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3149f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3149f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3149f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3149f,0f,0f,0f,0.8129f,0f,0f,0f,-0.0201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0043f,0.0002f,-0.3125f,0.0043f,0.9994f,0.0357f,1.375f,0f,0.0357f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0043f,0.0002f,0.3125f,-0.0043f,0.9994f,-0.0357f,1.375f,0f,-0.0357f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3152089566804732,"py":0.7504052973521763,"pz":-0.022340970837901385,"ry":0.008888366796441005,"rx":2.0484864703657477}}}