# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.314f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.314f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.314f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.314f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.314f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0027f,0.0001f,-0.3125f,0.0027f,0.9994f,0.0345f,1.375f,0f,0.0345f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0027f,0.0001f,0.3125f,-0.0027f,0.9994f,-0.0345f,1.375f,0f,-0.0345f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.31421698833798567,"py":0.7503738360290267,"pz":-0.021545468988955128,"ry":0.005432532128509138,"rx":1.9755270482431682}}}