# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3134f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0185f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3134f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0185f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3134f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0185f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3134f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0185f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3134f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0185f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0016f,0.0001f,-0.3125f,0.0016f,0.9995f,0.0329f,1.375f,0f,0.0329f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0016f,0.0001f,0.3125f,-0.0016f,0.9995f,-0.0329f,1.375f,0f,-0.0329f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3135012417620721,"py":0.7503398999418536,"pz":-0.020585356695485564,"ry":0.0030264348962418808,"rx":1.8874654327079672}}}