# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.313f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.313f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.313f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.313f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.313f,0f,0f,0f,0.8128f,0f,0f,0f,-0.0175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0009f,0f,-0.3125f,0.0009f,0.9995f,0.0311f,1.375f,0f,0.0311f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0009f,0f,0.3125f,-0.0009f,0.9995f,-0.0311f,1.375f,0f,-0.0311f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.313069841009504,"py":0.7503033710923547,"pz":-0.019462710824742532,"ry":0.001628324573317741,"rx":1.7844976484494044}}}