# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3129f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0164f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3129f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0164f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3129f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0164f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3129f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0164f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3129f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0164f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0007f,0f,-0.3125f,0.0007f,0.9996f,0.0291f,1.375f,0f,0.0291f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0007f,0f,0.3125f,-0.0007f,0.9996f,-0.0291f,1.375f,0f,-0.0291f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.31292829883204537,"py":0.750264631429315,"pz":-0.018180644019418636,"ry":0.0011431057105824038,"rx":1.6669134209213607}}}