# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3134f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3134f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3134f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3134f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3134f,0f,0f,0f,0.8127f,0f,0f,0f,-0.0136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0016f,0f,-0.3125f,0.0016f,0.9997f,0.0242f,1.375f,0f,0.0242f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0016f,0f,0.3125f,-0.0016f,0.9997f,-0.0242f,1.375f,0f,-0.0242f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3135234264462488,"py":0.7501846249272507,"pz":-0.015155846100059985,"ry":0.0022764330028337554,"rx":1.389519965065047}}}