# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
summon minecraft:armor_stand ^0 ^-1 ^0 {Tags:["aj.global.bone.root.child","aj.global.bone.root.child.locator","aj.global.bone.root.decendant","aj.global.bone.root.decendant.locator","aj.global.bone.root.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.hitbox","aj.new","aj.spite.bone.root.child","aj.spite.bone.root.child.locator","aj.spite.bone.root.decendant","aj.spite.bone.root.decendant.locator","aj.spite.bone.root.tree","aj.spite.entity","aj.spite.locator","aj.spite.locator.hitbox","aj.spite.node","aj.spite.node.hitbox"]}
execute as @n[ type=minecraft:armor_stand, tag=aj.spite.locator.hitbox, tag=aj.new, distance=..1 ] run function animated_java:spite/zzz/summon/as_data_entity/as_locator/hitbox
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.locator_hitbox set from storage animated_java:gu out
data modify entity @s data.locators.hitbox.uuid set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.spite.node.diamond_sword] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_diamond_sword set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.spite.node.right_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_arm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.spite.node.left_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_arm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.spite.node.head] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.spite.node.left_wing] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_wing set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.spite.node.right_wing] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_wing set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.spite.node.body] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_body set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.spite.node.hip] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_hip set from storage animated_java:gu out