# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.spite.root] run return 0
execute if entity @s[tag=aj.spite.animation.idle01.playing] run function animated_java:spite/animations/idle01/zzz/on_tick
execute if entity @s[tag=aj.spite.animation.death01.playing] run function animated_java:spite/animations/death01/zzz/on_tick
execute if entity @s[tag=aj.spite.animation.chargingstart01.playing] run function animated_java:spite/animations/chargingstart01/zzz/on_tick
execute if entity @s[tag=aj.spite.animation.charging01.playing] run function animated_java:spite/animations/charging01/zzz/on_tick
execute if entity @s[tag=aj.spite.animation.attack01.playing] run function animated_java:spite/animations/attack01/zzz/on_tick
execute if entity @s[tag=aj.spite.animation.summoning01.playing] run function animated_java:spite/animations/summoning01/zzz/on_tick
execute if entity @s[tag=aj.spite.animation.fireball01.playing] run function animated_java:spite/animations/fireball01/zzz/on_tick
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:spite/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~