# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:beebs/animations/run03/zzz/apply_frame {frame: 16}
scoreboard players add @s aj.run03.frame 1