# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
playsound minecraft:boss.skurleton_and_beebs.pistol_shot hostile @a ~ ~ ~ 5
data merge entity @e[tag=aj.skurleton.node.gun,limit=1] {item:{components:{"minecraft:item_model":"minecraft:boss/skurleton_and_beebs/gun_firing"}}}