# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_jaw) {transformation: [-1f,0f,0f,0f,0f,0.999f,0.0436f,1.9999f,0f,0.0436f,-0.999f,-0.1195f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.999f,0.0436f,1.875f,0f,0.0436f,-0.999f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.2391f,0f,0f,0f,1.75f,0f,0f,0f,0.4327f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0.9914f,0f,0.1305f,-0.2391f,0f,1f,0f,1.75f,-0.1305f,0f,0.9914f,0.4327f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.2391f,0f,0f,0f,1.75f,0f,0f,0f,0.4327f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.2391f,0f,0f,0f,1.75f,0f,0f,0f,0.4327f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.2391f,0f,0f,0f,1.75f,0f,0f,0f,0.4327f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9914f,-0.1305f,0f,-0.3125f,0f,0f,-1f,1.75f,0.1305f,-0.9914f,0f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.8192f,0.5736f,0f,0.25f,0f,0f,-1f,1.75f,-0.5736f,-0.8192f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-0.8434f,0.5373f,0f,-0.125f,0.1391f,0.2183f,-0.9659f,1.125f,-0.519f,-0.8147f,-0.2588f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-0.8434f,-0.5373f,0f,0.125f,-0.1391f,0.2183f,-0.9659f,1.125f,0.519f,-0.8147f,-0.2588f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.875f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.23092112986246782,"py":1.7499999999999998,"pz":0.4946530383586314,"ry":352.5,"rx":-90},"center":{"px":1.5308084989341915e-17,"py":1.5,"pz":-0.125,"ry":0,"rx":0}}}