# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3175f,0f,0f,0f,0.8082f,0f,0f,0f,0.024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3175f,0f,0f,0f,0.8082f,0f,0f,0f,0.024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3175f,0f,0f,0f,0.8082f,0f,0f,0f,0.024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3175f,0f,0f,0f,0.8082f,0f,0f,0f,0.024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3175f,0f,0f,0f,0.8082f,0f,0f,0f,0.024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0089f,0.0001f,-0.3125f,0.0078f,0.8717f,0.4901f,1.2985f,0.0043f,0.49f,-0.8717f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0089f,0.0001f,0.3125f,-0.0078f,0.8833f,0.4687f,1.2985f,-0.0043f,0.4687f,-0.8833f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3180423273854643,"py":0.7537043917054729,"pz":-0.006633236854689029,"ry":0.007085626972639147,"rx":29.34444894172871}}}