# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3388f,0f,0f,0f,0.8f,0f,0f,0f,0.0404f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3388f,0f,0f,0f,0.8f,0f,0f,0f,0.0404f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3388f,0f,0f,0f,0.8f,0f,0f,0f,0.0404f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3388f,0f,0f,0f,0.8f,0f,0f,0f,0.0404f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3388f,0f,0f,0f,0.8f,0f,0f,0f,0.0404f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.9989f,0.0467f,-0.001f,-0.3125f,0.041f,0.8862f,0.4614f,1.2985f,0.0224f,0.4609f,-0.8872f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.9989f,-0.0467f,-0.001f,0.3125f,-0.041f,0.8667f,0.4972f,1.2985f,-0.0224f,0.4967f,-0.8676f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3416716567009442,"py":0.7445949981456246,"pz":0.011586508866366918,"ry":359.9384489975681,"rx":27.479483491136136}}}