# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3126f,0f,0f,0f,0.8143f,0f,0f,0f,0.0134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3126f,0f,0f,0f,0.8143f,0f,0f,0f,0.0134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3126f,0f,0f,0f,0.8143f,0f,0f,0f,0.0134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3126f,0f,0f,0f,0.8143f,0f,0f,0f,0.0134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3126f,0f,0f,0f,0.8143f,0f,0f,0f,0.0134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0002f,0f,-0.3125f,0.0002f,0.8609f,0.5088f,1.2985f,0.0001f,0.5088f,-0.8609f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0002f,0f,0.3125f,-0.0002f,0.8933f,0.4495f,1.2985f,-0.0001f,0.4495f,-0.8933f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.31265110759468945,"py":0.7604504067163279,"pz":-0.0183830776731847,"ry":0.000544663463017514,"rx":30.586604529276617}}}