# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3687f,0f,0f,0f,0.8073f,0f,0f,0f,0.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3687f,0f,0f,0f,0.8073f,0f,0f,0f,0.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3687f,0f,0f,0f,0.8073f,0f,0f,0f,0.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3687f,0f,0f,0f,0.8073f,0f,0f,0f,0.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3687f,0f,0f,0f,0.8073f,0f,0f,0f,0.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.995f,0.0998f,0f,-0.3125f,0.0876f,0.8732f,0.4794f,1.2985f,0.0479f,0.477f,-0.8776f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.995f,-0.0998f,0f,0.3125f,-0.0876f,0.8732f,0.4794f,1.2985f,-0.0479f,0.477f,-0.8776f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3748959076403823,"py":0.7527401599739222,"pz":0.0014969630622247432,"ry":0,"rx":28.648}}}