# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3159f,0f,0f,0f,0.7898f,0f,0f,0f,0.0595f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3159f,0f,0f,0f,0.7898f,0f,0f,0f,0.0595f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3159f,0f,0f,0f,0.7898f,0f,0f,0f,0.0595f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3159f,0f,0f,0f,0.7898f,0f,0f,0f,0.0595f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3159f,0f,0f,0f,0.7898f,0f,0f,0f,0.0595f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.006f,-0.0004f,-0.3125f,0.0053f,0.9043f,0.4269f,1.2985f,0.0029f,0.4269f,-0.9043f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.006f,0.0004f,0.3125f,-0.0053f,0.9094f,0.4159f,1.2985f,-0.0029f,0.4159f,-0.9094f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3162786719589735,"py":0.733305590862634,"pz":0.03284813960124627,"ry":359.97738740618115,"rx":25.2697149775269}}}