# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3168f,0f,0f,0f,0.7895f,0f,0f,0f,0.0602f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3168f,0f,0f,0f,0.7895f,0f,0f,0f,0.0602f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3168f,0f,0f,0f,0.7895f,0f,0f,0f,0.0602f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3168f,0f,0f,0f,0.7895f,0f,0f,0f,0.0602f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3168f,0f,0f,0f,0.7895f,0f,0f,0f,0.0602f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0076f,-0.0005f,-0.3125f,0.0067f,0.9049f,0.4257f,1.2985f,0.0037f,0.4257f,-0.9049f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0076f,0.0005f,0.3125f,-0.0067f,0.908f,0.419f,1.2985f,-0.0037f,0.4189f,-0.908f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3172754161843994,"py":0.7329549463621843,"pz":0.03360824611187818,"ry":359.9707906912739,"rx":25.193054456298917}}}