# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.313f,0f,0f,0f,0.8121f,0f,0f,0f,0.0172f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.313f,0f,0f,0f,0.8121f,0f,0f,0f,0.0172f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.313f,0f,0f,0f,0.8121f,0f,0f,0f,0.0172f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.313f,0f,0f,0f,0.8121f,0f,0f,0f,0.0172f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.313f,0f,0f,0f,0.8121f,0f,0f,0f,0.0172f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0009f,0f,-0.3125f,0.0008f,0.8647f,0.5022f,1.2985f,0.0004f,0.5022f,-0.8647f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0009f,0f,0.3125f,-0.0008f,0.8943f,0.4474f,1.2985f,-0.0004f,0.4474f,-0.8943f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.31306992265468003,"py":0.7580210390292119,"pz":-0.014236259087745173,"ry":0.0015800188998582598,"rx":30.14601775870058}}}