# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3129f,0f,0f,0f,0.8118f,0f,0f,0f,0.0177f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3129f,0f,0f,0f,0.8118f,0f,0f,0f,0.0177f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3129f,0f,0f,0f,0.8118f,0f,0f,0f,0.0177f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3129f,0f,0f,0f,0.8118f,0f,0f,0f,0.0177f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3129f,0f,0f,0f,0.8118f,0f,0f,0f,0.0177f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0007f,0f,-0.3125f,0.0006f,0.8653f,0.5013f,1.2985f,0.0003f,0.5013f,-0.8653f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0007f,0f,0.3125f,-0.0006f,0.893f,0.4501f,1.2985f,-0.0003f,0.4501f,-0.893f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3129283452619808,"py":0.7576909654444758,"pz":-0.01366744104838813,"ry":0.0011390101250867701,"rx":30.085729470121628}}}