# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
playsound minecraft:boss.skurleton_and_beebs.bone_crack hostile @a ~ ~ ~ 1 1 0.5