# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_jaw) {transformation: [-1f,-0.0061f,-0.0059f,-0.0008f,-0.0062f,0.9999f,0.0099f,1.625f,0.0058f,0.01f,-0.9999f,0.0012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,-0.0061f,-0.0059f,0f,-0.0062f,0.9999f,0.0099f,1.5f,0.0058f,0.01f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3507f,0f,0f,0f,0.8181f,0f,0f,0f,-0.1737f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3507f,0f,0f,0f,0.8181f,0f,0f,0f,-0.1737f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3507f,0f,0f,0f,0.8181f,0f,0f,0f,-0.1737f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3507f,0f,0f,0f,0.8181f,0f,0f,0f,-0.1737f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3507f,0f,0f,0f,0.8181f,0f,0f,0f,-0.1737f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.888f,0.12f,0.4439f,-0.2832f,0.1403f,0.99f,0.0131f,1.375f,-0.4379f,0.0739f,-0.896f,-0.1321f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3582024287549526,"py":0.7562373640690795,"pz":-0.1782809023243166,"ry":26.357776657757938,"rx":0.751716722882785}}}