# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_jaw) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5332f,0f,0f,-1f,0.3596f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4082f,0f,0f,-1f,0.3596f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3684f,0f,0f,0f,0.7828f,0f,0f,0f,0.0819f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3684f,0f,0f,0f,0.7828f,0f,0f,0f,0.0819f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3684f,0f,0f,0f,0.7828f,0f,0f,0f,0.0819f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3684f,0f,0f,0f,0.7828f,0f,0f,0f,0.0819f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3684f,0f,0f,0f,0.7828f,0f,0f,0f,0.0819f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-0.995f,0.0993f,-0.01f,-0.3125f,0.0876f,0.9167f,0.3899f,1.2985f,0.0479f,0.387f,-0.9208f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-0.995f,-0.0993f,0.01f,0.3125f,-0.0876f,0.9167f,0.3899f,1.2985f,-0.0479f,0.387f,-0.9208f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1f,0f,0f,0.125f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.8776f,0.4794f,1.4082f,0f,0.4794f,-0.8776f,0.3596f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3745841856013452,"py":0.7255522485112077,"pz":0.05774415135127167,"ry":359.3798681799699,"rx":22.945630253011217},"center":{"px":-2.2017338219162742e-17,"py":1.079093114782738,"pz":0.1797852101887015,"ry":0,"rx":28.648}}}