# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3126f,0f,0f,0f,0.8156f,0f,0f,0f,0.0112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3126f,0f,0f,0f,0.8156f,0f,0f,0f,0.0112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3126f,0f,0f,0f,0.8156f,0f,0f,0f,0.0112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3126f,0f,0f,0f,0.8156f,0f,0f,0f,0.0112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3126f,0f,0f,0f,0.8156f,0f,0f,0f,0.0112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0002f,0f,-0.3125f,0.0001f,0.8585f,0.5128f,1.2985f,0.0001f,0.5128f,-0.8585f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0002f,0f,0.3125f,-0.0001f,0.8954f,0.4454f,1.2985f,-0.0001f,0.4454f,-0.8954f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.31260388408033773,"py":0.761915977590842,"pz":-0.020849622478480268,"ry":0.00042645935866403306,"rx":30.849624635546093}}}