# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3129f,0f,0f,0f,0.8162f,0f,0f,0f,0.0102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3129f,0f,0f,0f,0.8162f,0f,0f,0f,0.0102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3129f,0f,0f,0f,0.8162f,0f,0f,0f,0.0102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3129f,0f,0f,0f,0.8162f,0f,0f,0f,0.0102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3129f,0f,0f,0f,0.8162f,0f,0f,0f,0.0102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0007f,0f,-0.3125f,0.0006f,0.8575f,0.5145f,1.2985f,0.0004f,0.5145f,-0.8575f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0007f,0f,0.3125f,-0.0006f,0.8963f,0.4435f,1.2985f,-0.0004f,0.4435f,-0.8963f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3129585540537054,"py":0.7625724771038545,"pz":-0.02194588659057567,"ry":0.0019851234480370294,"rx":30.966764038518754}}}