# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3165f,0f,0f,0f,0.792f,0f,0f,0f,0.055f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3165f,0f,0f,0f,0.792f,0f,0f,0f,0.055f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3165f,0f,0f,0f,0.792f,0f,0f,0f,0.055f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3165f,0f,0f,0f,0.792f,0f,0f,0f,0.055f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3165f,0f,0f,0f,0.792f,0f,0f,0f,0.055f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0071f,-0.0004f,-0.3125f,0.0062f,0.9005f,0.4349f,1.2985f,0.0034f,0.4349f,-0.9005f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0071f,0.0007f,0.3125f,-0.0062f,0.9187f,0.395f,1.2985f,-0.0034f,0.395f,-0.9187f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3169293352018657,"py":0.7357026233813707,"pz":0.02783802448556738,"ry":359.9774002203849,"rx":25.77890217967497}}}