# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3134f,0f,0f,0f,0.8123f,0f,0f,0f,0.0168f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3134f,0f,0f,0f,0.8123f,0f,0f,0f,0.0168f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3134f,0f,0f,0f,0.8123f,0f,0f,0f,0.0168f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3134f,0f,0f,0f,0.8123f,0f,0f,0f,0.0168f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3134f,0f,0f,0f,0.8123f,0f,0f,0f,0.0168f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0016f,0f,-0.3125f,0.0014f,0.8643f,0.5029f,1.2985f,0.0008f,0.5029f,-0.8643f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0016f,0.0001f,0.3125f,-0.0014f,0.8956f,0.4449f,1.2985f,-0.0008f,0.4449f,-0.8956f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.31350142171144135,"py":0.7582718958397241,"pz":-0.014666734288173,"ry":0.0028622937061300036,"rx":30.19168984507389}}}