# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.313f,0f,0f,0f,0.8114f,0f,0f,0f,0.0183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.313f,0f,0f,0f,0.8114f,0f,0f,0f,0.0183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.313f,0f,0f,0f,0.8114f,0f,0f,0f,0.0183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.313f,0f,0f,0f,0.8114f,0f,0f,0f,0.0183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.313f,0f,0f,0f,0.8114f,0f,0f,0f,0.0183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0009f,0f,-0.3125f,0.0008f,0.8659f,0.5002f,1.2985f,0.0004f,0.5002f,-0.8659f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0009f,0f,0.3125f,-0.0008f,0.8915f,0.4531f,1.2985f,-0.0004f,0.4531f,-0.8915f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.31307949721651385,"py":0.7572840256901195,"pz":-0.012963732328822752,"ry":0.0014599365149479127,"rx":30.01120778573268}}}