# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.3134f,0f,0f,0f,0.811f,0f,0f,0f,0.019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.3134f,0f,0f,0f,0.811f,0f,0f,0f,0.019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.3134f,0f,0f,0f,0.811f,0f,0f,0f,0.019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.3134f,0f,0f,0f,0.811f,0f,0f,0f,0.019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.3134f,0f,0f,0f,0.811f,0f,0f,0f,0.019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0.0016f,0f,-0.3125f,0.0014f,0.8667f,0.4988f,1.2985f,0.0008f,0.4988f,-0.8667f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,-0.0016f,0f,0.3125f,-0.0014f,0.8899f,0.4562f,1.2985f,-0.0008f,0.4562f,-0.8899f,0.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.3135234740489986,"py":0.7568035200974362,"pz":-0.012129226652480063,"ry":0.002409280659264823,"rx":29.92292809781599}}}