# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.ravaged_mind.node.left_leg] at @s run function animated_java:ravaged_mind/variants/damaged/zzz/apply_to_node_left_leg
execute on passengers if entity @s[tag=aj.ravaged_mind.node.right_leg] at @s run function animated_java:ravaged_mind/variants/damaged/zzz/apply_to_node_right_leg
execute on passengers if entity @s[tag=aj.ravaged_mind.node.arms] at @s run function animated_java:ravaged_mind/variants/damaged/zzz/apply_to_node_arms
execute on passengers if entity @s[tag=aj.ravaged_mind.node.head] at @s run function animated_java:ravaged_mind/variants/damaged/zzz/apply_to_node_head
execute on passengers if entity @s[tag=aj.ravaged_mind.node.body] at @s run function animated_java:ravaged_mind/variants/damaged/zzz/apply_to_node_body
return 1