# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:skurleton/animations/riding01/zzz/apply_frame {frame: 30}
scoreboard players add @s aj.riding01.frame 1