# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:skurleton/animations/pause_all
scoreboard players set @s aj.ridingswordswap03.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:skurleton/animations/ridingswordswap03/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only