# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:ravaged_mind/root/on_tick/select_locator_controller with entity @s data.locators.controller
function animated_java:ravaged_mind/root/on_tick/select_locator_center with entity @s data.locators.center