# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
setblock 1059 121 1021 redstone_block
playsound minecraft:entity.skeleton.step hostile @a ~ ~ ~ 1 1 0.5