# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chbidoki_plushie.node.hair03] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_hair03 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chbidoki_plushie.node.hair02] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_hair02 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chbidoki_plushie.node.hair01] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_hair01 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chbidoki_plushie.node.right_horn_tip] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_horn_tip set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chbidoki_plushie.node.right_horn] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_horn set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chbidoki_plushie.node.left_horn_tip] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_horn_tip set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chbidoki_plushie.node.left_horn] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_horn set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chbidoki_plushie.node.right_ear] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_ear set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chbidoki_plushie.node.left_ear] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_ear set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chbidoki_plushie.node.right_twin_tail] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_twin_tail set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chbidoki_plushie.node.head] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chbidoki_plushie.node.left_twin_tail] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_twin_tail set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chbidoki_plushie.node.right_leg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_leg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chbidoki_plushie.node.left_leg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_leg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chbidoki_plushie.node.right_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_arm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chbidoki_plushie.node.left_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_arm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chbidoki_plushie.node.tail] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_tail set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chbidoki_plushie.node.body] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_body set from storage animated_java:gu out