# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:skurleton/animations/sneaked01/zzz/apply_frame {frame: 200}
scoreboard players add @s aj.sneaked01.frame 1