# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.run03.frame matches 17.. run scoreboard players set @s aj.run03.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.run03.frame
execute at @s run function animated_java:beebs/animations/run03/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.run03.frame 1