# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '0f7f715c95de7908b105824ad7c194aa87fcbbba8849d8b910fe74003ab406fe'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack