# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
particle poof ~ ~ ~ 0 0 0 1 100 force
particle minecraft:enchanted_hit ~ ~ ~ 0 0 0 1 50 force
playsound minecraft:entity.player.teleport hostile @a ~ ~ ~ 1 0.647
playsound minecraft:entity.lightning_bolt.thunder hostile @a ~ ~ ~ 1 1.75
function the_darkest_mansion:spite/summon_three_vex