# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:spite/at_locator {name:"center",command:"function the_darkest_mansion:summoning_particles"}
function animated_java:spite/at_locator {name:"center",command:"function the_darkest_mansion:summoning_particles"}
function animated_java:spite/at_locator {name:"center",command:"function the_darkest_mansion:summoning_particles"}
function animated_java:spite/at_locator {name:"center",command:"function the_darkest_mansion:summoning_particles"}
playsound minecraft:weather.rain hostile @a ~ ~ ~ 0.7 0.65