# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.spite.node.right_arm] at @s run function animated_java:spite/variants/damaged/zzz/apply_to_node_right_arm
execute on passengers if entity @s[tag=aj.spite.node.left_arm] at @s run function animated_java:spite/variants/damaged/zzz/apply_to_node_left_arm
execute on passengers if entity @s[tag=aj.spite.node.head] at @s run function animated_java:spite/variants/damaged/zzz/apply_to_node_head
execute on passengers if entity @s[tag=aj.spite.node.left_wing] at @s run function animated_java:spite/variants/damaged/zzz/apply_to_node_left_wing
execute on passengers if entity @s[tag=aj.spite.node.right_wing] at @s run function animated_java:spite/variants/damaged/zzz/apply_to_node_right_wing
execute on passengers if entity @s[tag=aj.spite.node.body] at @s run function animated_java:spite/variants/damaged/zzz/apply_to_node_body
execute on passengers if entity @s[tag=aj.spite.node.hip] at @s run function animated_java:spite/variants/damaged/zzz/apply_to_node_hip
return 1