# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [-1f,0f,0f,-0.1875f,0f,1f,-0.0071f,0.733f,0f,-0.0071f,-1f,-0.5352f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1) {transformation: [-1f,0f,0f,0.1875f,0f,1f,-0.0071f,0.7366f,0f,-0.0071f,-1f,-0.5342f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-0.996f,0.0855f,-0.0269f,-0.1897f,0.0877f,0.9918f,-0.093f,0.7352f,0.0187f,-0.095f,-0.9953f,0.1839f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3) {transformation: [-0.9895f,-0.138f,0.0425f,0.1885f,-0.1322f,0.9842f,0.1181f,0.7389f,-0.0581f,0.1112f,-0.9921f,0.1906f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tie) {transformation: [-1f,0f,0f,0f,0f,1f,0.0019f,0.7182f,0f,0.0019f,-1f,0.5219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mlg_glasses) {transformation: [-1f,0f,0f,0f,0f,0.9925f,0.1224f,1.0029f,0f,0.1224f,-0.9925f,0.6439f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9925f,0.1224f,0.9018f,0f,0.1224f,-0.9925f,0.4425f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9647f,0.2633f,1.1267f,0f,0.2633f,-0.9647f,-0.144f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":1.0928076890400505e-17,"py":0.852595877633195,"pz":-0.0892345196836268,"ry":0,"rx":15.267339425659491}}}