# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [-1f,0f,0f,-0.1875f,0f,0.9872f,0.1593f,0.7855f,0f,0.1593f,-0.9872f,-0.3898f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1) {transformation: [-1f,0f,0f,0.1875f,0f,0.9998f,-0.0221f,0.7396f,0f,-0.0221f,-0.9998f,-0.3838f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.1875f,0f,0.6428f,-0.766f,0.8712f,0f,-0.766f,-0.6428f,0.3554f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3) {transformation: [-1f,0f,0f,0.1875f,0f,0.766f,-0.6428f,0.7997f,0f,-0.6428f,-0.766f,0.4278f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tie) {transformation: [-1f,0f,0f,0f,0f,0.9459f,-0.3246f,1.0492f,0f,-0.3246f,-0.9459f,0.6471f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mlg_glasses) {transformation: [-1f,0f,0f,0f,0f,0.999f,-0.0436f,1.3209f,0f,-0.0436f,-0.999f,0.6847f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.999f,-0.0436f,1.1878f,0f,-0.0436f,-0.999f,0.5028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9914f,-0.1305f,1.1682f,0f,-0.1305f,-0.9914f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute on vehicle unless entity @s[tag=aj.transforms_only] as $(locator_center) positioned ^0 ^0.9366409965 ^0.0315621557 rotated ~0 ~-7.5 run function animated_java:beebs/animations/run02/zzz/frames/12_locator_center
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":-3.865249298494147e-18,"py":0.9366409965356197,"pz":0.031562155726739205,"ry":0,"rx":-7.5}}}