# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [-1f,0f,0f,-0.1875f,0f,0.761f,0.6487f,0.8645f,0f,0.6487f,-0.761f,-0.4599f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1) {transformation: [-1f,0f,0f,0.1875f,0f,0.8137f,0.5812f,0.8264f,0f,0.5812f,-0.8137f,-0.4624f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.1875f,0f,0.9451f,0.3268f,0.7529f,0f,0.3268f,-0.9451f,0.2843f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3) {transformation: [-1f,0f,0f,0.1875f,0f,0.8609f,0.5087f,0.7751f,0f,0.5087f,-0.8609f,0.3485f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tie) {transformation: [-1f,0f,0f,0f,0f,0.9982f,-0.0607f,0.919f,0f,-0.0607f,-0.9982f,0.6087f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mlg_glasses) {transformation: [-1f,0f,0f,0f,0f,0.9824f,0.1866f,1.1711f,0f,0.1866f,-0.9824f,0.7019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9824f,0.1866f,1.0833f,0f,0.1866f,-0.9824f,0.4944f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9978f,0.067f,1.1875f,0f,0.067f,-0.9978f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":2.0841048405635445e-18,"py":0.9296921465616748,"pz":-0.017018007494198156,"ry":0,"rx":3.838834764831844}}}