# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [-1f,0f,0f,-0.1875f,0f,0.9986f,0.0529f,0.8645f,0f,0.0529f,-0.9986f,-0.491f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1) {transformation: [-1f,0f,0f,0.1875f,0f,0.9966f,0.0825f,0.8614f,0f,0.0825f,-0.9966f,-0.4914f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.1875f,0f,0.7526f,0.6585f,0.876f,0f,0.6585f,-0.7526f,0.267f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3) {transformation: [-1f,0f,0f,0.1875f,0f,0.8972f,0.4417f,0.8384f,0f,0.4417f,-0.8972f,0.3251f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tie) {transformation: [-1f,0f,0f,0f,0f,0.9965f,-0.0841f,0.9352f,0f,-0.0841f,-0.9965f,0.59f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mlg_glasses) {transformation: [-1f,0f,0f,0f,0f,0.9878f,0.1558f,1.2007f,0f,0.1558f,-0.9878f,0.6912f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9878f,0.1558f,1.1065f,0f,0.1558f,-0.9878f,0.4865f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9914f,0.1305f,1.25f,0f,0.1305f,-0.9914f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":4.127174876864771e-18,"py":0.985823010629041,"pz":-0.033700940383286596,"ry":0,"rx":7.5}}}