# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [-1f,0f,0f,-0.1875f,0f,0.988f,-0.1546f,0.8476f,0f,-0.1546f,-0.988f,-0.485f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1) {transformation: [-1f,0f,0f,0.1875f,0f,0.9955f,-0.0948f,0.8476f,0f,-0.0948f,-0.9955f,-0.485f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.1875f,0f,0.749f,0.6626f,0.887f,0f,0.6626f,-0.749f,0.2743f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3) {transformation: [-1f,0f,0f,0.1875f,0f,0.9637f,0.2668f,0.8715f,0f,0.2668f,-0.9637f,0.3355f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tie) {transformation: [-1f,0f,0f,0f,0f,0.9951f,-0.0985f,0.9448f,0f,-0.0985f,-0.9951f,0.5954f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mlg_glasses) {transformation: [-1f,0f,0f,0f,0f,0.9928f,0.1197f,1.2158f,0f,0.1197f,-0.9928f,0.69f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9928f,0.1197f,1.1141f,0f,0.1197f,-0.9928f,0.4889f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9936f,0.1131f,1.2469f,0f,0.1131f,-0.9936f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":3.561552556847302e-18,"py":0.984405717143435,"pz":-0.029082283637429124,"ry":0,"rx":6.495190528383289}}}