# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [-1f,0f,0f,-0.1875f,0f,0.9063f,-0.4226f,0.8035f,0f,-0.4226f,-0.9063f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1) {transformation: [-1f,0f,0f,0.1875f,0f,0.9397f,-0.342f,0.7951f,0f,-0.342f,-0.9397f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.1875f,0f,0.9897f,0.1431f,0.9042f,0f,0.1431f,-0.9897f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3) {transformation: [-1f,0f,0f,0.1875f,0f,0.9704f,-0.2416f,0.8793f,0f,-0.2416f,-0.9704f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tie) {transformation: [-1f,0f,0f,0f,0f,0.9789f,-0.2044f,1.0055f,0f,-0.2044f,-0.9789f,0.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mlg_glasses) {transformation: [-1f,0f,0f,0f,0f,0.9998f,0.0218f,1.2826f,0f,0.0218f,-0.9998f,0.6902f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9998f,0.0218f,1.1617f,0f,0.0218f,-0.9998f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.2242f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":-3.0814879110195774e-33,"py":0.9742365782682796,"pz":2.7755575615628914e-17,"ry":0,"rx":-3.552713678800501e-15}}}