# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:ravaged_mind/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.ravaged_mind.node.left_leg] run data merge entity @s { transformation: [-1f,0f,0f,0.125f,0f,1f,0f,-1.25f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.ravaged_mind.node.right_leg] run data merge entity @s { transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,-1.25f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.ravaged_mind.node.arms] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,0.4617f,-0.887f,-0.625f,0f,-0.887f,-0.4617f,0.0625f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.ravaged_mind.node.head] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.4375f,0f,0f,-1f,0.125f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.ravaged_mind.node.body] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,-1.25f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }