# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:ravaged_mind rig_hash set value '0f7f715c95de7908b105824ad7c194aa87fcbbba8849d8b910fe74003ab406fe'
scoreboard objectives add aj.idle01.frame dummy
scoreboard objectives add aj.walk01.frame dummy
scoreboard objectives add aj.charging01.frame dummy
scoreboard objectives add aj.death01.frame dummy
scoreboard objectives add aj.target01.frame dummy