# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_leg) {transformation: [-1f,0f,0f,0.125f,0f,1f,0f,-1.25f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.9999f,0.0151f,-1.2518f,0f,0.0151f,-0.9999f,0.2542f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arms) {transformation: [-1f,0f,0f,0f,0f,0.7405f,-0.6721f,-0.648f,0f,-0.6721f,-0.7405f,0.1792f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9884f,0.1518f,-0.4756f,0f,0.1518f,-0.9884f,0.2759f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9821f,0.1885f,-1.25f,0f,0.1885f,-0.9821f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":-1.1540690178819279e-17,"py":-0.758960888354937,"pz":0.09423688680568436,"ry":0,"rx":10.863728757031314}}}