# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_leg) {transformation: [-1f,0f,0f,0.125f,0f,1f,0f,-1.25f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,-1.2565f,0f,0f,-1f,0.2527f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arms) {transformation: [-1f,0f,0f,0f,0f,0.6756f,-0.7373f,-0.6453f,0f,-0.7373f,-0.6756f,0.1701f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.999f,-0.0436f,-0.4715f,0f,-0.0436f,-0.999f,0.2642f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9848f,0.1736f,-1.25f,0f,0.1736f,-0.9848f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^0 ^-2 ^0 rotated ~0 ~0 run function animated_java:ravaged_mind/animations/target01/zzz/frames/13_locator_controller
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":-1.0632884247878856e-17,"py":-0.7575961234938959,"pz":0.08682408883346517,"ry":0,"rx":10.000000000000002}}}