# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_leg) {transformation: [-1f,0f,0f,0.125f,0f,1f,0f,-1.25f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.9768f,-0.2141f,-1.1574f,0f,-0.2141f,-0.9768f,0.1578f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arms) {transformation: [-1f,0f,0f,0f,0f,0.1836f,-0.983f,-0.6222f,0f,-0.983f,-0.1836f,0.0206f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9805f,-0.1964f,-0.431f,0f,-0.1964f,-0.9805f,0.0705f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9978f,-0.0668f,-1.25f,0f,-0.0668f,-0.9978f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":4.087667356257059e-18,"py":-0.7511153574027303,"pz":-0.03337833699563868,"ry":0,"rx":-3.827722283113839}}}