# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_leg) {transformation: [-1f,0f,0f,0.125f,0f,1f,0f,-1.25f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.9997f,0.0232f,-1.2072f,0f,0.0232f,-0.9997f,0.2635f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arms) {transformation: [-1f,0f,0f,0f,0f,0.6494f,-0.7605f,-0.6495f,0f,-0.7605f,-0.6494f,0.184f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.8954f,0.4453f,-0.4779f,0f,0.4453f,-0.8954f,0.2822f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9805f,0.1964f,-1.25f,0f,0.1964f,-0.9805f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":-1.2027292151785947e-17,"py":-0.7597401319093053,"pz":0.09821029345081224,"ry":0,"rx":11.327722283113836}}}