# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:ravaged_mind/animations/idle01/zzz/apply_frame {frame: 80}
scoreboard players add @s aj.idle01.frame 1