# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:ravaged_mind/animations/pause_all
tag @s add aj.ravaged_mind.animation.idle01.playing
scoreboard players set @s aj.idle01.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:ravaged_mind/animations/idle01/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only