# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:beebs/remove/this/as_data
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '685c14a2a3cff9fa5238f2a52646f709c19de0ed9053dd5999e775456049ce45'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack