# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [-0.5f,0f,0.866f,0.2851f,0f,1f,0f,0.75f,-0.866f,0f,-0.5f,-0.3811f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1) {transformation: [-0.5f,0f,0.866f,0.4726f,0f,1f,0f,0.75f,-0.866f,0f,-0.5f,-0.0564f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-0.5f,0f,0.866f,-0.3644f,0f,1f,0f,0.75f,-0.866f,0f,-0.5f,-0.0061f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3) {transformation: [-0.5f,0f,0.866f,-0.1769f,0f,1f,0f,0.75f,-0.866f,0f,-0.5f,0.3186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tie) {transformation: [-0.2064f,-0.4554f,0.866f,-0.5413f,-0.9109f,0.4127f,0f,0.9688f,-0.3574f,-0.7888f,-0.5f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mlg_glasses) {transformation: [-0.5f,0f,0.866f,-0.5954f,0f,1f,0f,1.25f,-0.866f,0f,-0.5f,0.3437f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-0.5f,0f,0.866f,-0.433f,0f,1f,0f,1.125f,-0.866f,0f,-0.5f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-0.5f,0f,0.866f,0.1083f,0f,1f,0f,1.1875f,-0.866f,0f,-0.5f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":0,"py":0.9375,"pz":0,"ry":59.999999999999986,"rx":0}}}