# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_jaw) {transformation: [-1.025f,0f,0f,0f,0f,0.8406f,0.5866f,1.6062f,0f,0.5866f,-0.8406f,0.1786f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9914f,0.1305f,1.4822f,0f,0.1305f,-0.9914f,0.1623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.456f,0f,0f,0f,0.8616f,0f,0f,0f,0.3527f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.456f,0f,0f,0f,0.8616f,0f,0f,0f,0.3527f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.456f,0f,0f,0f,0.8616f,0f,0f,0f,0.3527f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.456f,0f,0f,0f,0.8616f,0f,0f,0f,0.3527f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.456f,0f,0f,0f,0.8616f,0f,0f,0f,0.3527f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [0.9656f,0.2552f,0.0494f,-0.3125f,-0.254f,0.8863f,0.3872f,1.3602f,0.0551f,-0.3865f,0.9207f,0.1353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [0.973f,-0.2306f,-0.0103f,0.3125f,0.2154f,0.8909f,0.3998f,1.3602f,-0.083f,-0.3912f,0.9165f,0.1353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.4719829715437084,"py":0.8062471213361716,"pz":0.37681772267219105,"ry":176.93087991688932,"rx":22.782738177670435}}}