# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_jaw) {transformation: [-1.025f,0f,0f,0f,0f,0.8959f,0.4981f,1.6069f,0f,0.4981f,-0.8959f,0.171f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9976f,0.0694f,1.4822f,0f,0.0694f,-0.9976f,0.1623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.4522f,0f,0f,0f,0.8883f,0f,0f,0f,0.4078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.4522f,0f,0f,0f,0.8883f,0f,0f,0f,0.4078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.4522f,0f,0f,0f,0.8883f,0f,0f,0f,0.4078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.4522f,0f,0f,0f,0.8883f,0f,0f,0f,0.4078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.4522f,0f,0f,0f,0.8883f,0f,0f,0f,0.4078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [0.9656f,0.2483f,0.0768f,-0.3125f,-0.254f,0.8389f,0.4814f,1.3602f,0.0551f,-0.4844f,0.8731f,0.1353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [0.973f,-0.2288f,-0.0304f,0.3125f,0.2154f,0.8527f,0.4759f,1.3602f,-0.083f,-0.4696f,0.879f,0.1353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.46767628498494385,"py":0.8358878987642777,"pz":0.4380252592028735,"ry":174.9698832572064,"rx":28.778512509530852}}}