# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_jaw) {transformation: [-1.025f,0f,0f,0f,0f,0.922f,0.4477f,1.6071f,0f,0.4477f,-0.922f,0.1682f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9989f,0.0468f,1.4822f,0f,0.0468f,-0.9989f,0.1623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.4395f,0f,0f,0f,0.9581f,0f,0f,0f,0.5076f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.4395f,0f,0f,0f,0.9581f,0f,0f,0f,0.5076f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.4395f,0f,0f,0f,0.9581f,0f,0f,0f,0.5076f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.4395f,0f,0f,0f,0.9581f,0f,0f,0f,0.5076f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.4395f,0f,0f,0f,0.9581f,0f,0f,0f,0.5076f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [0.9656f,0.2258f,0.1288f,-0.3125f,-0.254f,0.7148f,0.6516f,1.3602f,0.0551f,-0.6619f,0.7476f,0.1353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [0.973f,-0.22f,-0.0696f,0.3125f,0.2154f,0.7571f,0.6168f,1.3602f,-0.083f,-0.6151f,0.7841f,0.1353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.4536021424428486,"py":0.9134404844947706,"pz":0.5489588402131856,"ry":170.22692992074795,"rx":40.66077040763962}}}