# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_jaw) {transformation: [-1.025f,0f,0f,0f,0f,0.929f,0.4332f,1.6071f,0f,0.4332f,-0.929f,0.1678f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.999f,0.0436f,1.4822f,0f,0.0436f,-0.999f,0.1623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_sword) {transformation: [0f,0f,0f,-0.4309f,0f,0f,0f,1.0004f,0f,0f,0f,0.5512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_gun) {transformation: [0f,0f,0f,-0.4309f,0f,0f,0f,1.0004f,0f,0f,0f,0.5512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bonemeal) {transformation: [0f,0f,0f,-0.4309f,0f,0f,0f,1.0004f,0f,0f,0f,0.5512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye01) {transformation: [0f,0f,0f,-0.4309f,0f,0f,0f,1.0004f,0f,0f,0f,0.5512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_dye02) {transformation: [0f,0f,0f,-0.4309f,0f,0f,0f,1.0004f,0f,0f,0f,0.5512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [0.9656f,0.2104f,0.1526f,-0.3125f,-0.254f,0.6396f,0.7255f,1.3602f,0.0551f,-0.7393f,0.6711f,0.1353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [0.973f,-0.2131f,-0.0885f,0.3125f,0.2154f,0.7005f,0.6804f,1.3602f,-0.083f,-0.6811f,0.7275f,0.1353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"righthand":{"px":-0.44400199034568,"py":0.9604304001180239,"pz":0.5973661813221902,"ry":167.19060932476984,"rx":46.512413362757016}}}