# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.spite.animation.idle01.playing
tag @s remove aj.spite.animation.death01.playing
tag @s remove aj.spite.animation.chargingstart01.playing
tag @s remove aj.spite.animation.charging01.playing
tag @s remove aj.spite.animation.attack01.playing
tag @s remove aj.spite.animation.summoning01.playing
tag @s remove aj.spite.animation.fireball01.playing