# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:skurleton/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.skurleton.node.jaw] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.625f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.skurleton.node.head] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.skurleton.node.sword] run data merge entity @s { transformation: [1f,0f,0f,-0.3125f,0f,0f,-1f,0.8125f,0f,1f,0f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.skurleton.node.gun] run data merge entity @s { transformation: [1f,0f,0f,-0.3125f,0f,0f,-1f,0.8125f,0f,1f,0f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.skurleton.node.bonemeal] run data merge entity @s { transformation: [1f,0f,0f,-0.3125f,0f,0f,-1f,0.8125f,0f,1f,0f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.skurleton.node.dye01] run data merge entity @s { transformation: [1f,0f,0f,-0.3125f,0f,0f,-1f,0.8125f,0f,1f,0f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.skurleton.node.dye02] run data merge entity @s { transformation: [1f,0f,0f,-0.3125f,0f,0f,-1f,0.8125f,0f,1f,0f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.skurleton.node.rightarm] run data merge entity @s { transformation: [-1f,0f,0f,-0.3125f,0f,1f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.skurleton.node.leftarm] run data merge entity @s { transformation: [-1f,0f,0f,0.3125f,0f,1f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.skurleton.node.rightleg] run data merge entity @s { transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.skurleton.node.leftleg] run data merge entity @s { transformation: [-1f,0f,0f,0.125f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.skurleton.node.body] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }