# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [0f,-1f,0f,0.1875f,-0.7071f,0f,-0.7071f,0.4956f,0.7071f,0f,-0.7071f,-0.1768f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1) {transformation: [0f,-1f,0f,0.1875f,-0.7071f,0f,-0.7071f,0.7607f,0.7071f,0f,-0.7071f,-0.4419f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [0f,-1f,0f,0.1875f,-0.7071f,0f,-0.7071f,1.0259f,0.7071f,0f,-0.7071f,0.3536f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3) {transformation: [0f,-1f,0f,0.1875f,-0.7071f,0f,-0.7071f,1.2911f,0.7071f,0f,-0.7071f,0.0884f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tie) {transformation: [0.8198f,-0.5727f,0f,-0.0313f,-0.4049f,-0.5797f,-0.7071f,1.3794f,0.4049f,0.5797f,-0.7071f,0.4419f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mlg_glasses) {transformation: [0f,-1f,0f,-0.3125f,-0.7071f,0f,-0.7071f,1.4236f,0.7071f,0f,-0.7071f,0.4861f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [0f,-1f,0f,-0.1875f,-0.7071f,0f,-0.7071f,1.2911f,0.7071f,0f,-0.7071f,0.3536f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [0f,-1f,0f,-0.25f,-0.7071f,0f,-0.7071f,0.8491f,0.7071f,0f,-0.7071f,-0.0884f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":0,"py":0.9375,"pz":0,"ry":8.526512829121202e-14,"rx":-44.99999999999999}}}