# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [0f,0f,1f,0.4375f,0f,-1f,0f,1.125f,1f,0f,0f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1) {transformation: [0f,0f,1f,0.4375f,0f,-1f,0f,1.125f,1f,0f,0f,-0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [0f,0f,1f,-0.3125f,0f,-1f,0f,1.125f,1f,0f,0f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3) {transformation: [0f,0f,1f,-0.3125f,0f,-1f,0f,1.125f,1f,0f,0f,-0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tie) {transformation: [0f,0f,1f,-0.625f,0.8767f,-0.481f,0f,0.9062f,0.481f,0.8767f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mlg_glasses) {transformation: [0f,0f,1f,-0.6875f,0f,-1f,0f,0.625f,1f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [0f,0f,1f,-0.5f,0f,-1f,0f,0.75f,1f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [0f,0f,1f,0.125f,0f,-1f,0f,0.6875f,1f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":0,"py":0.9375,"pz":0,"ry":90.00000000000003,"rx":6.315038368681387e-14}}}