# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:skurleton/animations/ridinggun03/zzz/apply_frame {frame: 30}
scoreboard players add @s aj.ridinggun03.frame 1