# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
playsound minecraft:boss.skurleton_and_beebs.skurleton_calling hostile @a ~ ~ ~ 10