# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:skurleton/remove/this/as_data
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '044fed56d878e5749415ecf3cff69b085dc49639802deba6cb1e496c88dbde6a'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack