# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [-1f,0f,0f,-0.1875f,0f,0.3479f,0.9375f,0.7908f,0f,0.9375f,-0.3479f,-0.4497f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1) {transformation: [-1f,0f,0f,0.1875f,0f,0.4782f,0.8782f,0.7283f,0f,0.8782f,-0.4782f,-0.4524f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.1875f,0f,0.9659f,-0.2588f,0.7312f,0f,-0.2588f,-0.9659f,0.2985f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3) {transformation: [-1f,0f,0f,0.1875f,0f,0.9397f,0.342f,0.7285f,0f,0.342f,-0.9397f,0.3609f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tie) {transformation: [-1f,0f,0f,0f,0f,0.8434f,-0.5373f,0.8112f,0f,-0.5373f,-0.8434f,0.6147f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mlg_glasses) {transformation: [-1f,0f,0f,0f,0f,0.9763f,0.2164f,0.9606f,0f,0.2164f,-0.9763f,0.7027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9763f,0.2164f,0.8791f,0f,0.2164f,-0.9763f,0.4926f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.999f,0.0436f,1.0625f,0f,0.0436f,-0.999f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":1.3500284828591207e-18,"py":0.8072855211838685,"pz":-0.011023819143601774,"ry":0,"rx":2.5}}}