# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [-1f,0f,0f,-0.1875f,0f,0.9331f,0.3595f,0.8125f,0f,0.3595f,-0.9331f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1) {transformation: [-1f,0f,0f,0.1875f,0f,0.9428f,0.3332f,0.8125f,0f,0.3332f,-0.9428f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.1875f,0f,0.8832f,0.469f,0.8033f,0f,0.469f,-0.8832f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3) {transformation: [-1f,0f,0f,0.1875f,0f,0.887f,0.4617f,0.75f,0f,0.4617f,-0.887f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tie) {transformation: [-1f,0f,0f,0f,0f,0.984f,-0.178f,0.8438f,0f,-0.178f,-0.984f,0.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mlg_glasses) {transformation: [-1f,0f,0f,0f,0f,0.9962f,0.0872f,1.0301f,0f,0.0872f,-0.9962f,0.6977f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9962f,0.0872f,0.9219f,0f,0.0872f,-0.9962f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.0625f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":0,"py":0.8125,"pz":0,"ry":0,"rx":0}}}