# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [-1f,0f,0f,-0.1875f,0f,0.9733f,-0.2296f,0.7982f,0f,-0.2296f,-0.9733f,-0.4295f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1) {transformation: [-1f,0f,0f,0.1875f,0f,0.9842f,-0.1772f,0.803f,0f,-0.1772f,-0.9842f,-0.4296f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.1875f,0f,0.8365f,0.548f,0.8261f,0f,0.548f,-0.8365f,0.32f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3) {transformation: [-1f,0f,0f,0.1875f,0f,0.9671f,0.2546f,0.7912f,0f,0.2546f,-0.9671f,0.3836f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tie) {transformation: [-1f,0f,0f,0f,0f,0.997f,-0.0773f,0.867f,0f,-0.0773f,-0.997f,0.6314f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mlg_glasses) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0053f,1.0783f,0f,-0.0053f,-1f,0.6905f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0053f,0.9523f,0f,-0.0053f,-1f,0.5037f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9995f,-0.0308f,1.0625f,0f,-0.0308f,-0.9995f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute on vehicle unless entity @s[tag=aj.transforms_only] as $(locator_center) positioned ^0 ^0.8164750391 ^0.0076526239 rotated ~0 ~-1.767766953 run function animated_java:beebs/animations/run05/zzz/frames/3_locator_center
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":-9.371761319200976e-19,"py":0.8164750391074178,"pz":0.0076526238632444454,"ry":0,"rx":-1.7677669529663687}}}