# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [-1f,0f,0f,-0.1875f,0f,0.887f,-0.4617f,0.7808f,0f,-0.4617f,-0.887f,-0.4255f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1) {transformation: [-1f,0f,0f,0.1875f,0f,0.9239f,-0.3827f,0.7991f,0f,-0.3827f,-0.9239f,-0.4263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.1875f,0f,0.9866f,0.1629f,0.8288f,0f,0.1629f,-0.9866f,0.3231f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3) {transformation: [-1f,0f,0f,0.1875f,0f,0.9763f,-0.2164f,0.8595f,0f,-0.2164f,-0.9763f,0.3843f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tie) {transformation: [-1f,0f,0f,0f,0f,0.999f,-0.0436f,0.8767f,0f,-0.0436f,-0.999f,0.6338f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mlg_glasses) {transformation: [-1f,0f,0f,0f,0f,0.999f,-0.0436f,1.0979f,0f,-0.0436f,-0.999f,0.6867f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.999f,-0.0436f,0.9649f,0f,-0.0436f,-0.999f,0.5049f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.999f,-0.0436f,1.0625f,0f,-0.0436f,-0.999f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":-1.3208886730272386e-18,"py":0.8181903680252025,"pz":0.010785874539066237,"ry":0,"rx":-2.5}}}