# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [-1f,0f,0f,-0.1875f,0f,0.9918f,-0.1279f,0.7626f,0f,-0.1279f,-0.9918f,-0.4266f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1) {transformation: [-1f,0f,0f,0.1875f,0f,0.9858f,-0.168f,0.8011f,0f,-0.168f,-0.9858f,-0.428f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.1875f,0f,0.8039f,-0.5947f,0.8169f,0f,-0.5947f,-0.8039f,0.3219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3) {transformation: [-1f,0f,0f,0.1875f,0f,0.7811f,-0.6244f,0.7943f,0f,-0.6244f,-0.7811f,0.3853f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tie) {transformation: [-1f,0f,0f,0f,0f,0.8998f,-0.4363f,0.8716f,0f,-0.4363f,-0.8998f,0.6326f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mlg_glasses) {transformation: [-1f,0f,0f,0f,0f,1f,0.0066f,1.0799f,0f,0.0066f,-1f,0.6927f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0.0066f,0.9561f,0f,0.0066f,-1f,0.5044f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9993f,-0.037f,1.0625f,0f,-0.037f,-0.9993f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute on vehicle unless entity @s[tag=aj.transforms_only] as $(locator_center) positioned ^0 ^0.8172937714 ^0.0091599994 rotated ~0 ~-2.1193976626 run function animated_java:beebs/animations/run05/zzz/frames/5_locator_center
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":-1.1217763957178542e-18,"py":0.8172937713710933,"pz":0.009159999409616537,"ry":0,"rx":-2.1193976625564344}}}