# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [-1f,0f,0f,-0.1875f,0f,0.7494f,0.6622f,0.7444f,0f,0.6622f,-0.7494f,-0.4318f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1) {transformation: [-1f,0f,0f,0.1875f,0f,0.9306f,0.3659f,0.8069f,0f,0.3659f,-0.9306f,-0.4329f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.1875f,0f,0.522f,-0.853f,0.7947f,0f,-0.853f,-0.522f,0.3174f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3) {transformation: [-1f,0f,0f,0.1875f,0f,0.6622f,-0.7494f,0.7591f,0f,-0.7494f,-0.6622f,0.3806f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tie) {transformation: [-1f,0f,0f,0f,0f,0.6622f,-0.7494f,0.8573f,0f,-0.7494f,-0.6622f,0.6288f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mlg_glasses) {transformation: [-1f,0f,0f,0f,0f,0.9976f,0.0691f,1.0449f,0f,0.0691f,-0.9976f,0.6981f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9976f,0.0691f,0.9332f,0f,0.0691f,-0.9976f,0.5024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9998f,-0.0181f,1.0625f,0f,-0.0181f,-0.9998f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":-5.508103652575782e-19,"py":0.8147998917360317,"pz":0.004497707956621244,"ry":0,"rx":-1.0355339059327386}}}