# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [-1f,0f,0f,-0.1875f,0f,0.4923f,0.8704f,0.7722f,0f,0.8704f,-0.4923f,-0.4405f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1) {transformation: [-1f,0f,0f,0.1875f,0f,0.7512f,0.66f,0.7463f,0f,0.66f,-0.7512f,-0.4408f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.1875f,0f,0.7995f,-0.6006f,0.7648f,0f,-0.6006f,-0.7995f,0.3095f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3) {transformation: [-1f,0f,0f,0.1875f,0f,0.9685f,-0.2489f,0.7449f,0f,-0.2489f,-0.9685f,0.3718f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tie) {transformation: [-1f,0f,0f,0f,0f,0.7283f,-0.6852f,0.8361f,0f,-0.6852f,-0.7283f,0.6227f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mlg_glasses) {transformation: [-1f,0f,0f,0f,0f,0.9901f,0.1407f,1.0018f,0f,0.1407f,-0.9901f,0.7016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9901f,0.1407f,0.9044f,0f,0.1407f,-0.9901f,0.4984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9999f,0.0102f,1.0625f,0f,0.0102f,-0.9999f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":3.1423903957697795e-19,"py":0.8112333985813083,"pz":-0.0025659564847249072,"ry":0,"rx":0.5865828381745484}}}