# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @e[tag=RavagedMind,sort=nearest,limit=1] TDMRandSound run random value 0..1
execute if entity @e[tag=RavagedMind,scores={TDMRandSound=1}] run playsound minecraft:entity.ravager.ambient hostile @a ~ ~ ~ 1 1.5