# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:skurleton/animations/pause_all
tag @s add aj.skurleton.animation.ridinggun01.playing
scoreboard players set @s aj.ridinggun01.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:skurleton/animations/ridinggun01/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only