# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute as @e[tag=aj.ravaged_mind.root,sort=nearest,limit=1] run function animated_java:ravaged_mind/variants/damaged/apply
playsound minecraft:entity.ravager.death hostile @a ~ ~ ~ 1 1.5