# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'dd349ee88bec2c5112026180c888820749c723d7695ebdc299a24ad56e4d4bb1'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack