# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
playsound minecraft:sfx.sword_slash hostile @a ~ ~ ~ 0.3
execute rotated as @s run particle minecraft:sweep_attack ^ ^0.4 ^1.5 0 0 0 0.008 1 force