# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [-1f,0f,0f,-0.1875f,0f,0.989f,-0.1478f,0.7473f,0f,-0.1478f,-0.989f,-0.4893f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1) {transformation: [-1f,0f,0f,0.1875f,0f,0.9799f,0.1994f,0.7473f,0f,0.1994f,-0.9799f,-0.4893f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-0.9848f,0.1726f,-0.0182f,-0.1875f,0.1735f,0.9803f,-0.0946f,0.7172f,0.0015f,-0.0964f,-0.9953f,0.2639f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3) {transformation: [-0.9914f,-0.1304f,0.0042f,0.1875f,-0.1267f,0.9698f,0.2083f,0.7296f,-0.0312f,0.206f,-0.978f,0.2656f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tie) {transformation: [-1f,0f,0f,0f,0f,1f,0.0087f,0.7727f,0f,0.0087f,-1f,0.5873f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mlg_glasses) {transformation: [-1f,0f,0f,0f,0f,0.91f,0.4147f,0.9809f,0f,0.4147f,-0.91f,0.7077f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.91f,0.4147f,0.9449f,0f,0.4147f,-0.91f,0.4852f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9903f,0.1392f,1.0938f,0f,0.1392f,-0.9903f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":4.409924546268363e-18,"py":0.8287863451945991,"pz":-0.03600976664732006,"ry":0,"rx":8}}}