# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:spite/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.spite.node.diamond_sword] run data merge entity @s { transformation: [-1f,0f,0f,-0.3437f,0f,0f,1f,0f,0f,1f,0f,0.125f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.spite.node.right_arm] run data merge entity @s { transformation: [-1f,0f,0f,-0.3437f,0f,1f,0f,0.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.spite.node.left_arm] run data merge entity @s { transformation: [-1f,0f,0f,0.3438f,0f,1f,0f,0.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.spite.node.head] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.5f,0f,0f,-1f,0.0625f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.spite.node.left_wing] run data merge entity @s { transformation: [-1.3333f,0f,0f,0.0625f,0f,1.3333f,0f,0.375f,0f,0f,-1.3333f,-0.125f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.spite.node.right_wing] run data merge entity @s { transformation: [-1.3333f,0f,0f,-0.0625f,0f,1.3333f,0f,0.375f,0f,0f,-1.3333f,-0.125f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.spite.node.body] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.25f,0f,0f,-1f,0.0625f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.spite.node.hip] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.25f,0f,0f,-1f,0.0625f,0f,0f,0f,1f], start_interpolation: 0 }