# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @e[tag=Spite,limit=1] TDMRandSound run random value 0..2
execute if entity @e[tag=Spite,scores={TDMRandSound=2}] run playsound minecraft:entity.vex.ambient hostile @a ~ ~ ~ 1 0.5