# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:spite/remove/this/as_data
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '9c7d19210c3053e5e83640cdc48da1f31c3f9e3545955c616e9178d5fae38b46'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack