# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.ravaged_mind.root] run return 0
execute if entity @s[tag=aj.ravaged_mind.animation.idle01.playing] run function animated_java:ravaged_mind/animations/idle01/zzz/on_tick
execute if entity @s[tag=aj.ravaged_mind.animation.walk01.playing] run function animated_java:ravaged_mind/animations/walk01/zzz/on_tick
execute if entity @s[tag=aj.ravaged_mind.animation.charging01.playing] run function animated_java:ravaged_mind/animations/charging01/zzz/on_tick
execute if entity @s[tag=aj.ravaged_mind.animation.death01.playing] run function animated_java:ravaged_mind/animations/death01/zzz/on_tick
execute if entity @s[tag=aj.ravaged_mind.animation.target01.playing] run function animated_java:ravaged_mind/animations/target01/zzz/on_tick
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:ravaged_mind/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~