# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:skurleton/animations/ridingswordrun01/zzz/apply_frame {frame: 8}
scoreboard players add @s aj.ridingswordrun01.frame 1