# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.ravaged_mind.animation.idle01.playing
tag @s remove aj.ravaged_mind.animation.walk01.playing
tag @s remove aj.ravaged_mind.animation.charging01.playing
tag @s remove aj.ravaged_mind.animation.death01.playing
tag @s remove aj.ravaged_mind.animation.target01.playing