# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:skurleton/root/on_tick/select_locator_righthand with entity @s data.locators.righthand
function animated_java:skurleton/root/on_tick/select_locator_center with entity @s data.locators.center