# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [-1f,0f,0f,-0.1875f,0f,1f,0f,0.75f,0f,0f,-1f,-0.4375f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
$data merge entity $(bone_leg1) {transformation: [-1f,0f,0f,0.1875f,0f,1f,0f,0.75f,0f,0f,-1f,-0.4375f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.1875f,0f,1f,0f,0.75f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
$data merge entity $(bone_leg3) {transformation: [-1f,0f,0f,0.1875f,0f,1f,0f,0.75f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
$data merge entity $(bone_tie) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.9688f,0f,0f,-1f,0.625f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
$data merge entity $(bone_mlg_glasses) {transformation: [-0.9763f,-0.2146f,0.0283f,0f,-0.1773f,0.8678f,0.4643f,1.25f,-0.1241f,0.4483f,-0.8852f,0.75f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.125f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.1875f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":0,"py":0.9375,"pz":0,"ry":0,"rx":0}}}