# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
summon item ~ ~ ~ {Age:-32768,PickupDelay:32767,Motion:[0.0,0.25,0.05],Tags:["BeebsRemains"],Item:{id:"minecraft:mutton",count:1}}
playsound minecraft:entity.sheep.death hostile @a ~ ~ ~ 1 1 0.25