# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [-0.97f,0.2433f,0f,0.0006f,0.2433f,0.97f,0f,0.7731f,0f,0f,-1f,-0.4375f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
$data merge entity $(bone_leg1) {transformation: [-0.97f,0.2433f,0f,0.3643f,0.2433f,0.97f,0f,0.6819f,0f,0f,-1f,-0.4375f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
$data merge entity $(bone_leg2) {transformation: [-0.97f,0.2433f,0f,0.0006f,0.2433f,0.97f,0f,0.7731f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
$data merge entity $(bone_leg3) {transformation: [-0.97f,0.2433f,0f,0.3643f,0.2433f,0.97f,0f,0.6819f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
$data merge entity $(bone_tie) {transformation: [-0.97f,0.2433f,0f,0.2357f,0.2433f,0.97f,0f,0.9396f,0f,0f,-1f,0.625f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
$data merge entity $(bone_mlg_glasses) {transformation: [-0.9901f,0.003f,0.1403f,0.3041f,0.0655f,0.8939f,0.4435f,1.2125f,-0.1241f,0.4483f,-0.8852f,0.75f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
$data merge entity $(bone_head) {transformation: [-0.97f,0.2433f,0f,0.2737f,0.2433f,0.97f,0f,1.0912f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
$data merge entity $(bone_body) {transformation: [-0.97f,0.2433f,0f,0.2889f,0.2433f,0.97f,0f,1.1518f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":0.2280574153615783,"py":0.9093382568101909,"pz":2.7755575615628914e-17,"ry":0,"rx":-1.7655625192200634e-31}}}