# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [-0.444f,0.896f,0f,0.5888f,0.896f,0.444f,0f,0.501f,0f,0f,-1f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1) {transformation: [-0.444f,0.896f,0f,0.7553f,0.896f,0.444f,0f,0.165f,0f,0f,-1f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-0.444f,0.896f,0f,0.5888f,0.896f,0.444f,0f,0.501f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3) {transformation: [-0.444f,0.896f,0f,0.7553f,0.896f,0.444f,0f,0.165f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tie) {transformation: [-0.444f,0.896f,0f,0.868f,0.896f,0.444f,0f,0.4301f,0f,0f,-1f,0.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mlg_glasses) {transformation: [-0.5924f,0.6822f,0.4286f,1.12f,0.7961f,0.5776f,0.1808f,0.555f,-0.1241f,0.4483f,-0.8852f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-0.444f,0.896f,0f,1.008f,0.896f,0.444f,0f,0.4995f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-0.444f,0.896f,0f,1.064f,0.896f,0.444f,0f,0.5273f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":0.8400177524313812,"py":0.41626485030582483,"pz":9.71445146547012e-17,"ry":0,"rx":7.062250076880254e-31}}}