# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [-0.2955f,0.9553f,0f,0.6611f,0.9553f,0.2955f,0f,0.4008f,0f,0f,-1f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1) {transformation: [-0.2955f,0.9553f,0f,0.7719f,0.9553f,0.2955f,0f,0.0425f,0f,0f,-1f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-0.2955f,0.9553f,0f,0.6611f,0.9553f,0.2955f,0f,0.4008f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3) {transformation: [-0.2955f,0.9553f,0f,0.7719f,0.9553f,0.2955f,0f,0.0425f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tie) {transformation: [-0.2955f,0.9553f,0f,0.9255f,0.9553f,0.2955f,0f,0.2863f,0f,0f,-1f,0.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mlg_glasses) {transformation: [-0.4579f,0.7656f,0.4519f,1.1942f,0.8803f,0.4614f,0.1102f,0.3694f,-0.1241f,0.4483f,-0.8852f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-0.2955f,0.9553f,0f,1.0748f,0.9553f,0.2955f,0f,0.3325f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-0.2955f,0.9553f,0f,1.1345f,0.9553f,0.2955f,0f,0.3509f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":0.8956292319471449,"py":0.2770460771816973,"pz":1.1102230246251565e-16,"ry":0,"rx":0}}}