# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [-0.1704f,0.9854f,0f,0.7071f,0.9854f,0.1704f,0f,0.3125f,0f,0f,-1f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1) {transformation: [-0.1704f,0.9854f,0f,0.771f,0.9854f,0.1704f,0f,-0.057f,0f,0f,-1f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-0.1704f,0.9854f,0f,0.7071f,0.9854f,0.1704f,0f,0.3125f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3) {transformation: [-0.1704f,0.9854f,0f,0.771f,0.9854f,0.1704f,0f,-0.057f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tie) {transformation: [-0.1704f,0.9854f,0f,0.9546f,0.9854f,0.1704f,0f,0.165f,0f,0f,-1f,0.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mlg_glasses) {transformation: [-0.341f,0.8185f,0.4623f,1.2317f,0.9318f,0.3593f,0.0513f,0.213f,-0.1241f,0.4483f,-0.8852f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-0.1704f,0.9854f,0f,1.1086f,0.9854f,0.1704f,0f,0.1917f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-0.1704f,0.9854f,0f,1.1701f,0.9854f,0.1704f,0f,0.2023f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":0.9237936772125754,"py":0.15972317283997334,"pz":1.1102230246251565e-16,"ry":0,"rx":0}}}