# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leg0) {transformation: [-0.0768f,0.997f,0f,0.7334f,0.997f,0.0768f,0f,0.2445f,0f,0f,-1f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1) {transformation: [-0.0768f,0.997f,0f,0.7622f,0.997f,0.0768f,0f,-0.1293f,0f,0f,-1f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-0.0768f,0.997f,0f,0.7334f,0.997f,0.0768f,0f,0.2445f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3) {transformation: [-0.0768f,0.997f,0f,0.7622f,0.997f,0.0768f,0f,-0.1293f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tie) {transformation: [-0.0768f,0.997f,0f,0.9659f,0.997f,0.0768f,0f,0.0744f,0f,0f,-1f,0.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mlg_glasses) {transformation: [-0.2518f,0.8487f,0.4651f,1.2463f,0.9598f,0.2806f,0.0075f,0.096f,-0.1241f,0.4483f,-0.8852f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-0.0768f,0.997f,0f,1.1217f,0.997f,0.0768f,0f,0.0864f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-0.0768f,0.997f,0f,1.184f,0.997f,0.0768f,0f,0.0912f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"center":{"px":0.9347307837572854,"py":0.0720042491558022,"pz":1.1102230246251565e-16,"ry":0,"rx":0}}}